import type { Metadata } from 'next';
import { ArrowUpRight, Instagram, ShoppingBag, Workflow } from 'lucide-react';
import { setRequestLocale } from 'next-intl/server';
import { Link } from '@/i18n/routing';
import BreadcrumbStructuredData from '@/components/BreadcrumbStructuredData';
import { localizedMetadata } from '@/lib/seo/metadata';

const copy = {
  ka: { eyebrow: 'SOCIAL COMMERCE AI', title: 'სოციალური ქსელიდან შეკვეთამდე, ნაკლები ხელით შესრულებული ნაბიჯით.', description: 'Social Commerce AI ეხმარება Instagram-ის, TikTok-ისა და ონლაინ მაღაზიის გუნდებს მომხმარებლის კითხვებზე პასუხში, პროდუქტის შერჩევასა და შეკვეთის პროცესის ორგანიზებაში.', cta: 'შეაფასეთ თქვენი არხები', secondary: 'AI CRM ინტეგრაცია', useCases: [['პროდუქტის კითხვა', 'AI პასუხობს ფასზე, მახასიათებელზე, ხელმისაწვდომობასა და მიწოდების წესზე დამტკიცებული ცოდნით.'], ['შეკვეთის მიღება', 'მოთხოვნა გადადის სამუშაო პროცესში და გუნდს რჩება საჭირო კონტექსტი.'], ['გაყიდვის გაგრძელება', 'მომხმარებლის განზრახვა და შემდეგი ნაბიჯი CRM-ში იწერება.']], channels: [['Instagram და TikTok', 'მომხმარებლის საუბარი იწყებს გაყიდვების workflow-ს.'], ['პროდუქტის ცოდნა', 'პასუხები ეყრდნობა დამტკიცებულ კატალოგსა და წესებს.'], ['შეკვეთის ოპერაცია', 'მოთხოვნა გადადის სწორ გუნდთან ან ავტომატურ პროცესში.']], closingTitle: 'სოციალური კომერცია მუშაობს მაშინ, როცა საუბარი პროცესში გადადის.', closingText: 'ვაერთიანებთ არხებს, პროდუქტის ცოდნასა და CRM-ს ისე, რომ მომხმარებლის გამოცდილება და გუნდის ოპერაცია ერთ კონტექსტში დარჩეს.' },
  en: { eyebrow: 'SOCIAL COMMERCE AI', title: 'From social conversation to order with fewer manual steps.', description: 'Social Commerce AI helps Instagram, TikTok, and ecommerce teams answer product questions, guide selection, and organize the order workflow.', cta: 'Assess your channels', secondary: 'AI CRM integration', useCases: [['Product questions', 'AI answers questions about price, features, availability, and delivery using approved knowledge.'], ['Order intake', 'The request enters a workflow and the team keeps the context needed to act.'], ['Continue the sale', 'Customer intent and the next action are captured in the CRM.']], channels: [['Instagram and TikTok', 'A customer conversation can start the sales workflow.'], ['Product knowledge', 'Answers rely on an approved catalog and business rules.'], ['Order operations', 'The request reaches the right team or automated process.']], closingTitle: 'Social commerce works when conversation becomes an operation.', closingText: 'We connect channels, product knowledge, and CRM so the customer experience and team workflow keep one shared context.' },
} as const;

export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> {
  const { locale } = await params;
  return localizedMetadata({ locale, path: '/solutions/social-commerce-ai', title: { ka: 'Social Commerce AI და ონლაინ გაყიდვების ავტომატიზაცია', en: 'Social Commerce AI and online sales automation' }, description: { ka: copy.ka.description, en: copy.en.description } });
}

export default async function SocialCommercePage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  setRequestLocale(locale);
  const language = locale === 'en' ? 'en' : 'ka';
  const text = copy[language];
  return <main className="mx-auto max-w-7xl px-6 pb-24 pt-32 lg:px-8"><BreadcrumbStructuredData locale={language} items={[{ name: language === 'en' ? 'Home' : 'მთავარი', path: '' }, { name: 'Social Commerce AI', path: '/solutions/social-commerce-ai' }]} /><p className="font-heading text-xs font-bold tracking-[.16em] text-primary">{text.eyebrow}</p><h1 className="mt-5 max-w-4xl text-4xl font-semibold tracking-[-.05em] text-slate-950 dark:text-white sm:text-7xl">{text.title}</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-slate-600 dark:text-slate-300">{text.description}</p><div className="mt-10 flex flex-wrap gap-3"><Link href="/consultation" className="font-heading inline-flex items-center gap-2 rounded-full bg-black px-6 py-4 text-sm font-bold text-white dark:bg-white dark:text-black">{text.cta} <ArrowUpRight size={18}/></Link><Link href="/services/ai-crm-integration" className="font-heading inline-flex items-center gap-2 rounded-full border border-black/15 px-6 py-4 text-sm font-bold dark:border-white/15">{text.secondary}</Link></div><section className="mt-20 grid gap-4 md:grid-cols-3">{text.useCases.map(([title, description], index) => <article key={title} className="rounded-[1.75rem] border border-black/15 p-7 dark:border-white/15"><span className="font-heading text-xs font-bold text-neutral-500">0{index + 1}</span><h2 className="mt-14 text-xl font-semibold text-slate-950 dark:text-white">{title}</h2><p className="mt-4 leading-7 text-slate-600 dark:text-slate-300">{description}</p></article>)}</section><section className="mt-16 grid gap-4 sm:grid-cols-3">{text.channels.map(([title, description], index) => { const Icon = [Instagram, ShoppingBag, Workflow][index]; return <article key={title} className="rounded-[1.75rem] bg-neutral-100 p-6 dark:bg-[#171717]"><Icon size={22}/><h3 className="mt-8 text-lg font-semibold text-slate-950 dark:text-white">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-600 dark:text-slate-300">{description}</p></article>; })}</section><section className="mt-16 rounded-[2rem] bg-black p-8 text-white dark:bg-white dark:text-black sm:p-12"><h2 className="max-w-3xl text-3xl font-semibold tracking-[-.04em] sm:text-5xl">{text.closingTitle}</h2><p className="mt-5 max-w-2xl leading-8 text-neutral-300 dark:text-neutral-600">{text.closingText}</p></section></main>;
}
