import { ArrowUpRight, CalendarDays, Clock3 } from 'lucide-react';
import { Link } from '@/i18n/routing';
import { insights } from '@/data/insights';
import { getLocalizedInsight } from '@/data/localizedInsights';
import WorkflowDiagram from './WorkflowDiagram';

export default function BlogExperience({ locale }: { locale: 'ka' | 'en' }) {
  const english = locale === 'en';
  const localized = insights.map((item) => getLocalizedInsight(item.slug, locale)!);
  const featured = localized[0];
  const rest = localized.slice(1);
  return <main className="blog-experience">
    <section className="blog-hero"><div className="blog-container blog-hero__grid"><div><p className="blog-eyebrow"><span className="signal-dot" />IMI.GE / {english ? 'INSIGHTS' : 'ინსაითები'}</p><h1>{english ? <>Practical thinking for teams <em>building with AI.</em></> : <>სიღრმისეული მასალა მათთვის, ვინც AI-ს <em>რეალურ ოპერაციაში</em> ნერგავს.</>}</h1><p>{english ? 'Clear guidance on voice AI, RAG, CRM, and automation decisions, from the people mapping the workflows.' : 'წერილები ეფუძნება იმ კითხვებს, რომლებიც ჩნდება AI voice, RAG, CRM და automation სისტემების დაგეგმვისას.'}</p></div><div className="blog-hero__board"><div><span>{english ? 'EDITORIAL SIGNAL' : 'სარედაქციო სიგნალი'}</span><b>03</b></div><div className="blog-hero__board-line"><i /><i /><i /><i /></div><p>{english ? 'New field notes every week' : 'ახალი field note ყოველ კვირას'}</p></div></div></section>
      <section className="blog-container blog-featured"><Link href={`/blog/${featured.slug}`} className="blog-featured__card"><div className="blog-featured__visual"><span className="blog-index">01 / FEATURED</span><div className="insight-visual"><img src={featured.visual?.src} alt={featured.visual?.alt[locale]} /><span className="insight-visual__orbit insight-visual__orbit--one" /><span className="insight-visual__orbit insight-visual__orbit--two" /><span className="insight-visual__beam" /></div><span className="blog-visual-note">KNOWLEDGE / SIGNAL → ACTION</span></div><div className="blog-featured__content"><p className="blog-category">{featured.category}</p><h2>{featured.title}</h2><p className="blog-excerpt">{featured.excerpt}</p><div className="blog-meta"><span><CalendarDays size={14} />{new Date(featured.date).toLocaleDateString(english ? 'en-US' : 'ka-GE', { year: 'numeric', month: 'short', day: 'numeric' })}</span><span><Clock3 size={14} />{featured.readTime}</span><span className="blog-read">{english ? 'Read article' : 'წაიკითხეთ'} <ArrowUpRight size={15} /></span></div></div></Link></section>
      <section className="blog-container blog-workflow"><WorkflowDiagram locale={locale} compact /></section>
      <section className="blog-container blog-grid">{rest.map((insight, index) => <article className="blog-card" key={insight.slug}><Link href={`/blog/${insight.slug}`}><div className="blog-card__visual"><span className="blog-index">0{index + 2}</span><div className="insight-visual"><img src={insight.visual?.src} alt={insight.visual?.alt[locale]} /><span className="insight-visual__orbit insight-visual__orbit--one" /><span className="insight-visual__beam" /></div><span className="blog-visual-note">IMI FIELD NOTE / 0{index + 2}</span></div><div className="blog-card__body"><p className="blog-category">{insight.category}</p><h2>{insight.title}</h2><p className="blog-excerpt">{insight.excerpt}</p><div className="blog-meta"><span>{new Date(insight.date).toLocaleDateString(english ? 'en-US' : 'ka-GE', { year: 'numeric', month: 'short', day: 'numeric' })}</span><span>{insight.readTime}</span><ArrowUpRight size={16} /></div></div></Link></article>)}</section>
   </main>;
}
