import { ArrowUpRight, Bot, ChevronRight, Database, Mic, Search, Workflow } from 'lucide-react';
import { Link } from '@/i18n/routing';

const capabilities = [
  [Mic, 'Voice AI', 'Natural customer conversations, qualification, and intelligent handoff.'],
  [Database, 'Knowledge systems', 'Your documents and internal data become grounded, useful answers.'],
  [Bot, 'AI CRM', 'Every lead gets context, prioritization, and a clear next action.'],
  [Workflow, 'Automation', 'Repeatable work follows rules, approval points, and measurable outcomes.'],
] as const;

export default function EnglishHome() {
  return <main>
    <section className="bg-white px-5 pb-20 pt-32 text-[#171717] dark:bg-[#050505] dark:text-[#f7f7f7] sm:px-8 lg:pt-40"><div className="mx-auto max-w-7xl"><p className="font-heading text-xs font-bold tracking-[.16em] text-neutral-500 dark:text-neutral-400">IMI.GE / ARTIFICIAL INTELLIGENCE FOR BUSINESS</p><div className="mt-12 grid gap-12 lg:grid-cols-[1.15fr_.85fr] lg:items-end"><div><h1 className="max-w-4xl text-5xl font-semibold leading-[.95] tracking-[-.06em] sm:text-7xl xl:text-8xl">Which part of your business should work <span className="text-neutral-400 dark:text-neutral-500">smarter</span> tomorrow?</h1><p className="mt-9 max-w-xl text-lg leading-8 text-neutral-600 dark:text-neutral-400">IMI.GE builds AI systems that connect your customers, knowledge, CRM, and daily operations into one practical operating layer.</p><div className="mt-10 flex flex-col gap-3 sm:flex-row"><Link href="/consultation" className="font-heading inline-flex items-center justify-center gap-3 rounded-full bg-black px-6 py-4 text-sm font-bold text-white dark:bg-white dark:text-black">Start a consultation <ArrowUpRight size={18}/></Link><Link href="/services" className="font-heading inline-flex items-center justify-center gap-3 rounded-full border border-black/20 px-6 py-4 text-sm font-bold transition hover:bg-black hover:text-white dark:border-white/25 dark:hover:bg-white dark:hover:text-black">Explore services <ChevronRight size={18}/></Link></div></div><div className="rounded-[2rem] border border-black/15 bg-[#f4f4f4] p-5 dark:border-white/15 dark:bg-[#171717]"><div className="rounded-[1.5rem] border border-black/10 bg-white p-5 dark:border-white/10 dark:bg-[#0d0d0d]"><p className="font-heading text-xs font-bold tracking-[.14em] text-neutral-500">YOUR AI WORKSPACE</p><p className="mt-8 text-xl font-medium leading-snug">“We need a system that understands sales requests and routes every lead to the right person.”</p><div className="mt-8 flex items-center justify-between border-t border-black/10 pt-4 text-sm text-neutral-500 dark:border-white/10"><span>AI CRM / Sales</span><span className="font-heading text-black dark:text-white">Action ready</span></div></div><div className="mt-3 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-black p-4 text-white dark:bg-white dark:text-black"><p className="font-heading text-xs font-bold">Context</p><p className="mt-6 text-sm">CRM, calls, and messages.</p></div><div className="rounded-2xl border border-black/10 p-4 dark:border-white/10"><p className="font-heading text-xs font-bold">Control</p><p className="mt-6 text-sm text-neutral-600 dark:text-neutral-400">People review complex decisions.</p></div></div></div></div></div></section>
    <section className="border-y border-black/10 bg-[#f4f4f4] px-5 py-20 dark:border-white/10 dark:bg-[#111111] sm:px-8"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><h2 className="max-w-3xl text-4xl font-semibold leading-tight tracking-[-.04em] text-[#171717] dark:text-white sm:text-5xl">AI is not another tool. It is a new interface for the way your business works.</h2><Link href="/ai-readiness" className="font-heading text-sm font-bold text-[#171717] underline underline-offset-4 dark:text-white">Assess AI readiness</Link></div><div className="mt-14 grid border-t border-black/15 dark:border-white/15 md:grid-cols-4">{capabilities.map(([Icon, title, text], index) => <article key={title} className="border-b border-black/15 py-7 pr-8 dark:border-white/15 md:border-b-0 md:border-r md:px-7 first:pl-0 last:border-r-0"><span className="font-heading text-xs font-bold text-neutral-500">0{index + 1}</span><Icon className="mt-10" size={25}/><h3 className="mt-7 text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-7 text-neutral-600 dark:text-neutral-400">{text}</p></article>)}</div></div></section>
    <section className="bg-black px-5 py-24 text-white sm:px-8"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="font-heading text-xs font-bold tracking-[.16em] text-neutral-400">HOW WE WORK</p><h2 className="mt-5 text-4xl font-semibold leading-tight tracking-[-.04em]">A focused pilot. A measurable result. Then scale.</h2></div><div className="grid gap-4 sm:grid-cols-3">{[['01','Discover','Find one valuable business problem.'],['02','Implement','Connect knowledge, data, and workflow.'],['03','Own','Give your team a system they can manage.']].map(([number,title,text]) => <div key={number} className="border-t border-white/25 pt-5"><p className="font-heading text-xs font-bold text-neutral-400">{number}</p><h3 className="mt-9 text-lg font-semibold">{title}</h3><p className="mt-3 text-sm leading-7 text-neutral-400">{text}</p></div>)}</div></div></section>
    <section className="mx-auto max-w-5xl px-5 py-24 sm:px-8"><div className="border-t border-black/15 pt-12 dark:border-white/15"><p className="font-heading text-xs font-bold tracking-[.16em] text-neutral-500">READY TO START?</p><h2 className="mt-5 text-4xl font-semibold tracking-[-.04em] text-[#171717] dark:text-white">Bring one difficult process. We will map the next step.</h2><Link href="/assistant" className="font-heading mt-8 inline-flex items-center gap-2 rounded-full bg-black px-6 py-4 text-sm font-bold text-white dark:bg-white dark:text-black">Talk to the AI assistant <ArrowUpRight size={18}/></Link></div></section>
  </main>;
}
