import Image from 'next/image';
import { ArrowUpRight, Clock3 } from 'lucide-react';
import { Link } from '@/i18n/routing';
import { insights } from '@/data/insights';

const copy = [['Why strong AI assistants begin with knowledge architecture', 'RAG is more than answering questions. It creates a controlled path from trusted company knowledge to useful action.'], ['Voice AI that truly represents your brand', 'A quality voice agent knows what to answer, when to hand off, and what context to leave in your CRM.'], ['Where real AI automation ROI begins', 'The fastest results come from repeatable workflows with enough context and clear human control.']];

export default function EnglishInsights() {
  return <div className="relative overflow-hidden pt-32 pb-24"><div className="ai-grid pointer-events-none absolute inset-0 -z-10 opacity-40"/><section className="mx-auto max-w-7xl px-6 lg:px-8"><p className="font-heading text-xs font-bold tracking-[.18em] text-primary">IMI.GE INSIGHTS</p><h1 className="mt-5 max-w-4xl text-4xl font-semibold tracking-[-.05em] text-slate-950 dark:text-white sm:text-6xl">Practical thinking for teams building with AI.</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-slate-600 dark:text-slate-300">Clear guidance on voice AI, RAG, CRM, and automation decisions.</p></section><section className="mx-auto mt-16 grid max-w-7xl gap-6 px-6 md:grid-cols-3 lg:px-8">{insights.map((insight, index) => <article key={insight.slug} className="glass-panel overflow-hidden rounded-[2rem]"><div className="relative aspect-[16/10]"><Image src={insight.image} alt={copy[index]?.[0] ?? insight.title} fill sizes="(max-width: 768px) 100vw, 33vw" className="object-cover grayscale contrast-125"/></div><div className="p-6"><p className="font-heading text-xs font-bold tracking-[.14em] text-primary">{insight.category}</p><h2 className="mt-7 text-xl font-semibold text-slate-950 dark:text-white">{copy[index]?.[0] ?? insight.title}</h2><p className="mt-4 text-sm leading-7 text-slate-600 dark:text-slate-300">{copy[index]?.[1] ?? insight.excerpt}</p><div className="mt-7 flex items-center justify-between text-xs text-neutral-500"><span>{insight.readTime}</span><Link href={`/blog/${insight.slug}`} className="font-heading inline-flex items-center gap-2 font-bold text-slate-950 dark:text-white">Read article <ArrowUpRight size={16}/></Link></div></div></article>)}</section></div>;
}
