import { Cookie, FileText, Shield } from 'lucide-react';
import { legalDocuments, type LegalKind } from '@/data/legal';

export default function LocalizedLegalPage({ kind, locale, email = 'hello@imi.ge' }: { kind: LegalKind; locale: 'ka' | 'en'; email?: string }) {
  const document = legalDocuments[kind][locale];
  const Icon = kind === 'privacy' ? Shield : kind === 'terms' ? FileText : Cookie;
  const dateLabel = locale === 'en' ? 'Last updated' : 'განახლების თარიღი';
  return <div className="pt-40 pb-24 min-h-screen bg-gray-50 dark:bg-darker transition-colors duration-300"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><div className="text-center mb-20"><div className="inline-flex items-center justify-center p-4 bg-primary/10 rounded-2xl mb-8 border border-primary/20 shadow-lg shadow-primary/20"><Icon className="w-10 h-10 text-primary" /></div><h1 className="text-3xl md:text-5xl font-heading font-bold text-gray-900 dark:text-white mb-6 tracking-wide uppercase">{document.title}</h1><p className="text-lg text-gray-500 dark:text-gray-400 tracking-wide font-sans">{dateLabel}: {document.date}</p></div><div className="space-y-8">{document.sections.map(([heading, body]) => <section key={heading} className="p-8 md:p-10 rounded-[2rem] border border-gray-200 dark:border-white/10 bg-white dark:bg-white/5 shadow-xl"><h2 className="text-2xl font-heading font-bold text-gray-900 dark:text-white mb-6">{heading}</h2><p className="text-gray-600 dark:text-gray-300 leading-relaxed font-light">{body}</p></section>)}</div>{document.contactTitle && <div className="mt-20 p-10 rounded-[2.5rem] bg-gradient-to-br from-primary/10 to-secondary/10 border border-primary/20 text-center"><h2 className="text-2xl font-heading font-bold text-gray-900 dark:text-white mb-4">{document.contactTitle}</h2><p className="text-gray-600 dark:text-gray-400 mb-6">{document.contactText}</p><a href={`mailto:${email}`} className="text-primary font-bold hover:text-secondary transition-colors text-xl font-heading">{email}</a></div>}</div></div>;
}
