import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { ArrowUpRight, LockKeyhole, MessageSquareText, Network, Sparkles } from 'lucide-react';
import { setRequestLocale } from 'next-intl/server';
import { Link } from '@/i18n/routing';
import BreadcrumbStructuredData from '@/components/BreadcrumbStructuredData';
import { localizedMetadata } from '@/lib/seo/metadata';

type ServiceCopy = {
  eyebrow: string;
  title: string;
  description: string;
  outcomes: string[];
  outcomeDescriptions: string[];
  steps: string[];
  implementationTitle: string;
  implementationDescription: string;
};

const serviceCopy: Record<string, { ka: ServiceCopy; en: ServiceCopy }> = {
  'ai-voice-agents': {
    ka: { eyebrow: 'ხმოვანი AI', title: 'თქვენი ბრენდის ხმა, რომელიც ნებისმიერ დროს პასუხობს.', description: 'ვქმნით ქართულ და მრავალენოვან ხმოვან AI ასისტენტებსა და ჩატბოტებს, რომლებიც ბუნებრივად საუბრობენ, მართავენ დიალოგს და სწორ კონტექსტს გუნდამდე მიაქვთ.', outcomes: ['24/7 პასუხი და კვალიფიკაცია', 'გაყიდვებისა და CRM ინტეგრაცია', 'ხარისხის კონტროლი და ანალიტიკა'], outcomeDescriptions: ['მოთხოვნა მიიღება და კვალიფიცირდება მაშინაც, როცა გუნდი არ მუშაობს.', 'საუბრის შედეგი და მომხმარებლის კონტექსტი გადადის თქვენს სამუშაო პროცესში.', 'ვზომავთ პასუხის სისწორეს, გადამისამართებასა და გადაწყვეტილ საკითხებს.'], steps: ['სცენარის აღმოჩენა', 'ხმისა და ინტეგრაციის არქიტექტურა', 'პილოტი და ხარისხის გაზომვა'], implementationTitle: 'ხმოვანი AI იწყება მკაფიო საზღვრით.', implementationDescription: 'ვადგენთ, რა უნდა იცოდეს ასისტენტმა, რა უნდა შეაგროვოს და როდის უნდა ჩაერთოს ადამიანი.' },
    en: { eyebrow: 'VOICE AI', title: 'A brand voice that answers whenever your customers need it.', description: 'We build Georgian and multilingual voice assistants and chatbots that manage conversations naturally, capture the right context, and route work to your team.', outcomes: ['24/7 response and qualification', 'Sales and CRM integration', 'Quality control and analytics'], outcomeDescriptions: ['Requests are received and qualified even when your team is offline.', 'Conversation outcomes and customer context enter your existing workflow.', 'We measure answer accuracy, handoff quality, and resolved requests.'], steps: ['Discover the conversation', 'Design voice and integrations', 'Pilot and measure quality'], implementationTitle: 'Voice AI starts with a clear boundary.', implementationDescription: 'We define what the assistant can know, what it should collect, and when a person must take over.' },
  },
  'rag-internal-ai': {
    ka: { eyebrow: 'ცოდნის AI / RAG', title: 'კომპანიის ცოდნა, რომელსაც თქვენი გუნდი რეალურ დროში იყენებს.', description: 'შიდა AI ასისტენტი აერთიანებს წესებს, ხელშეკრულებებს, ოპერაციულ დოკუმენტაციასა და CRM მონაცემებს ერთი დაცული, წყაროზე მიბმული გამოცდილებისთვის.', outcomes: ['დოკუმენტებზე დაფუძნებული პასუხები', 'წვდომა როლებისა და უფლებების მიხედვით', 'უსაფრთხო ცოდნის ძიება'], outcomeDescriptions: ['პასუხი ეყრდნობა დამტკიცებულ წყაროს და არა დაუდასტურებელ ვარაუდს.', 'თითოეულ გუნდს ვაძლევთ მხოლოდ მისთვის დაშვებულ ცოდნაზე წვდომას.', 'ძიება, ციტირება და გამონაკლისები კონტროლირებად პროცესად იქცევა.'], steps: ['ცოდნის წყაროების რუკა', 'წვდომისა და retrieval-ის არქიტექტურა', 'პილოტი ერთ გუნდთან'], implementationTitle: 'RAG არის ცოდნის კონტროლირებული მიწოდება.', implementationDescription: 'ვიწყებთ ერთი გუნდისა და ერთი დოკუმენტური წყაროს კონკრეტული კითხვებით, შემდეგ კი ვაფართოებთ სისტემას გაზომვის საფუძველზე.' },
    en: { eyebrow: 'KNOWLEDGE AI / RAG', title: 'Company knowledge your team can use in real time.', description: 'An internal AI assistant connects policies, contracts, operating documents, and CRM data into one secure experience grounded in approved sources.', outcomes: ['Document-grounded answers', 'Role-based access', 'Secure knowledge search'], outcomeDescriptions: ['Answers rely on approved sources instead of unsupported model guesses.', 'Each team sees only the knowledge it is allowed to use.', 'Search, citations, and exceptions become a controlled workflow.'], steps: ['Map the knowledge sources', 'Design retrieval and access', 'Pilot with one team'], implementationTitle: 'RAG is controlled knowledge delivery.', implementationDescription: 'We start with concrete questions from one team and one document source, then expand based on measured quality.' },
  },
  'business-automation': {
    ka: { eyebrow: 'ოპერაციული AI', title: 'განმეორებადი ოპერაციები გადააბარეთ AI აგენტებს.', description: 'ვაპროექტებთ სამუშაო პროცესებს, რომლებიც ამოწმებს მონაცემს, ქმნის ჩანაწერს, გზავნის შეტყობინებას, ამუშავებს დოკუმენტს და რთულ შემთხვევას ადამიანთან აბრუნებს.', outcomes: ['გაყიდვები და ლიდების გადანაწილება', 'დოკუმენტებისა და მოთხოვნების დამუშავება', 'SLA და გამონაკლისების კონტროლი'], outcomeDescriptions: ['მოთხოვნა სწორ გუნდთან მიდის სრული კონტექსტით.', 'რუტინული შემოწმება და ჩანაწერების შექმნა ავტომატურად სრულდება.', 'სისტემა მკაფიოდ აჩერებს პროცესს მაშინ, როცა ადამიანის გადაწყვეტილებაა საჭირო.'], steps: ['პროცესის რუკა და KPI', 'აგენტის საზღვრები და ინტეგრაციები', 'რეალური პროცესის პილოტი'], implementationTitle: 'ავტომატიზაცია მხოლოდ იქ მუშაობს, სადაც საზღვარი ნათელია.', implementationDescription: 'ვზომავთ ხელით შრომას, შეცდომებსა და დაგვიანებას, შემდეგ ვქმნით აგენტს, რომელიც უსაფრთხოდ აბრუნებს გამონაკლისს ადამიანთან.' },
    en: { eyebrow: 'OPERATIONS AI', title: 'Hand repetitive operations to controlled AI agents.', description: 'We design workflows that validate data, create records, send notifications, process documents, and return complex cases to a person.', outcomes: ['Sales and lead routing', 'Document and request processing', 'SLA and exception control'], outcomeDescriptions: ['Requests reach the right team with the context needed to act.', 'Routine checks and record creation happen automatically.', 'The workflow stops clearly whenever a human decision is required.'], steps: ['Map the process and KPI', 'Define agent boundaries and integrations', 'Pilot in the real workflow'], implementationTitle: 'Automation works when its boundary is explicit.', implementationDescription: 'We measure manual effort, errors, and delay, then build an agent that safely returns exceptions to a responsible person.' },
  },
  'ai-native-web': {
    ka: { eyebrow: 'AI-ზე დაფუძნებული ვებ-პროდუქტი', title: 'ციფრული პროდუქტი, სადაც AI არქიტექტურის ნაწილია.', description: 'ვქმნით სწრაფ, SEO-ძლიერ ვებ-გამოცდილებებსა და ვებ-აპლიკაციებს, რომლებიც AI-ს, მონაცემებსა და კონვერსიის სამუშაო პროცესებს ერთ წარმოების სისტემაში აერთიანებს.', outcomes: ['პროდუქტის სტრატეგია და UX', 'AI-სთვის მზად backend არქიტექტურა', 'Core Web Vitals და ანალიტიკა'], outcomeDescriptions: ['ვიწყებთ მომხმარებლის ამოცანით და არა მხოლოდ ვიზუალური ფენით.', 'AI შესაძლებლობები ჩაშენებულია მონაცემთა, ავტორიზაციისა და API საზღვრებში.', 'სისწრაფე, ძიებაში ხილვადობა და ბიზნეს-მეტრიკა ერთად იზომება.'], steps: ['პროდუქტის აღმოჩენა', 'გამოცდილებისა და სისტემის არქიტექტურა', 'აშენება, გაშვება და მონიტორინგი'], implementationTitle: 'AI-native პროდუქტი იწყება რეალური სამუშაო პროცესით.', implementationDescription: 'ვქმნით სისტემას, სადაც ინტერფეისი, მონაცემები, AI და გაზომვა ერთ production-ready მოდელში მუშაობს.' },
    en: { eyebrow: 'AI-NATIVE WEB PRODUCT', title: 'A digital product where AI belongs in the architecture.', description: 'We build fast, search-ready websites and web applications that connect AI, data, and conversion workflows in one production system.', outcomes: ['Product strategy and UX', 'AI-ready backend architecture', 'Core Web Vitals and analytics'], outcomeDescriptions: ['We start with the user problem, not another visual layer.', 'AI capabilities fit inside clear data, authorization, and API boundaries.', 'Speed, search visibility, and business metrics are measured together.'], steps: ['Discover the product', 'Design experience and architecture', 'Build, launch, and monitor'], implementationTitle: 'An AI-native product starts with a real workflow.', implementationDescription: 'The interface, data, AI, and measurement work together as one production-ready system.' },
  },
  'ai-crm-integration': {
    ka: { eyebrow: 'AI CRM ინტეგრაცია', title: 'არსებული CRM აქციეთ გაყიდვების ინტელექტის სისტემად.', description: 'ვაერთიანებთ AI-ს თქვენს არსებულ CRM-სა და კომუნიკაციის არხებთან, რომ ლიდების შეფასება, კონტექსტის შეგროვება, follow-up და მომდევნო ნაბიჯის შერჩევა გამჭვირვალედ მუშაობდეს.', outcomes: ['ლიდების AI შეფასება', 'შეთავაზებული მომდევნო ნაბიჯი', 'CRM ჩანაწერების ავტომატური გამდიდრება'], outcomeDescriptions: ['გუნდი ხედავს რომელი მოთხოვნა მოითხოვს დაუყოვნებლივ ყურადღებას.', 'AI გვთავაზობს მოქმედებას, ხოლო პასუხისმგებლობა რჩება გუნდთან.', 'კომუნიკაციის კონტექსტი CRM-ში ხელით გადაწერის გარეშე ინახება.'], steps: ['მონაცემისა და funnel-ის აუდიტი', 'CRM ინტეგრაციის დიზაინი', 'მოქმედების ხარისხის პილოტი'], implementationTitle: 'CRM ინტეგრაცია უნდა ამცირებდეს კონტექსტის დაკარგვას.', implementationDescription: 'ვაერთიანებთ მონაცემს ისე, რომ AI-მ სწორი სიგნალი მიაწოდოს სწორ ადამიანს და არა უბრალოდ კიდევ ერთი შეტყობინება შექმნას.' },
    en: { eyebrow: 'AI CRM INTEGRATION', title: 'Turn your existing CRM into a sales intelligence system.', description: 'We connect AI to your CRM and communication channels so lead scoring, context capture, follow-up, and next actions work transparently.', outcomes: ['AI lead scoring', 'Next-action recommendations', 'Automatic CRM enrichment'], outcomeDescriptions: ['Your team can see which requests deserve attention first.', 'AI recommends an action while accountability stays with the team.', 'Conversation context is stored without another manual handoff.'], steps: ['Audit data and the funnel', 'Design CRM integrations', 'Pilot action quality'], implementationTitle: 'CRM integration should reduce lost context.', implementationDescription: 'We connect the data so AI gives the right signal to the right person instead of creating another notification.' },
  },
  'ai-first-crm': {
    ka: { eyebrow: 'CRM ტრანსფორმაცია', title: 'გადაიყვანეთ კომპანია AI-first CRM ოპერაციულ მოდელზე.', description: 'ვგეგმავთ CRM-ის სრულ გარდაქმნას: პროცესების აღმოჩენიდან მონაცემის მიგრაციამდე, ინტეგრაციებიდან AI აგენტებამდე. შედეგია სისტემა, რომელიც გაყიდვებს, მომსახურებასა და ოპერაციებს ერთ კონტექსტში მართავს.', outcomes: ['CRM არქიტექტურის გეგმა', 'მონაცემის მიგრაცია და ხარისხი', 'AI სამუშაო პროცესები თავიდანვე'], outcomeDescriptions: ['ახალი მოდელი იწყება პროცესისა და პასუხისმგებლობის მკაფიო რუკით.', 'მიგრაცია ხდება მონაცემის ხარისხისა და ბიზნესის უწყვეტობის დაცვით.', 'AI სამუშაო პროცესები თავიდანვე ერგება თქვენს ოპერაციულ წესებს.'], steps: ['მიმდინარე სისტემის აღმოჩენა', 'მიგრაციისა და მონაცემის გეგმა', 'ეტაპობრივი გადასვლა'], implementationTitle: 'CRM ტრანსფორმაცია მიგრაციაზე მეტია.', implementationDescription: 'ვქმნით ახალ ოპერაციულ მოდელს ისე, რომ გაყიდვები და მომსახურება გადასვლის პერიოდში არ გაჩერდეს.' },
    en: { eyebrow: 'CRM TRANSFORMATION', title: 'Move your company to an AI-first CRM operating model.', description: 'We plan the full CRM transformation from process discovery and data migration to integrations and AI agents, keeping sales, service, and operations connected.', outcomes: ['CRM architecture plan', 'Data migration and quality', 'AI workflows from day one'], outcomeDescriptions: ['The new model begins with a clear map of processes and ownership.', 'Migration protects data quality and business continuity.', 'AI workflows fit your operating rules from the start.'], steps: ['Discover the current system', 'Plan migration and data quality', 'Move in controlled stages'], implementationTitle: 'CRM transformation is more than migration.', implementationDescription: 'We build a new operating model without stopping sales or customer service during the transition.' },
  },
  'sales-intelligence': {
    ka: { eyebrow: 'გაყიდვების ინტელექტი', title: 'გაყიდვების გუნდი გადაწყვეტილებას უკეთესი სიგნალებით იღებს.', description: 'AI აანალიზებს ლიდების, კომუნიკაციისა და CRM მონაცემს, რათა გუნდი ფოკუსირდეს გარიგებებზე, სადაც რეალური პოტენციალი ან რისკი ჩანს.', outcomes: ['გარიგების რისკის სიგნალები', 'გაყიდვების პროგნოზი', 'მომდევნო საუკეთესო მოქმედება'], outcomeDescriptions: ['გუნდი ხედავს გარიგებებს, სადაც ჩარევა ან მხარდაჭერა ყველაზე მნიშვნელოვანია.', 'პროგნოზი ეფუძნება მიმდინარე სიგნალებს და არა მხოლოდ ინტუიციას.', 'მომდევნო მოქმედება კონტექსტითა და პასუხისმგებელი პირით არის განსაზღვრული.'], steps: ['სიგნალებისა და მონაცემის რუკა', 'მოდელისა და dashboard-ის დიზაინი', 'გაყიდვების გუნდთან შეფასება'], implementationTitle: 'ინტელექტი მოქმედებად სიგნალს უნდა ქმნიდეს.', implementationDescription: 'ვაერთიანებთ მონაცემს, რათა პროგნოზი და რისკის სიგნალი ყოველდღიურ გაყიდვების პროცესში გამოიყენებოდეს.' },
    en: { eyebrow: 'SALES INTELLIGENCE', title: 'Help sales teams decide with better signals.', description: 'AI analyzes lead, conversation, and CRM data so teams can focus on deals where real potential or risk is visible.', outcomes: ['Deal risk signals', 'Sales forecasting', 'Next-best action'], outcomeDescriptions: ['Teams see which deals need intervention or support first.', 'Forecasts use current signals rather than intuition alone.', 'The next action is defined with context and ownership.'], steps: ['Map signals and data', 'Design the model and dashboard', 'Evaluate with the sales team'], implementationTitle: 'Intelligence should produce an actionable signal.', implementationDescription: 'We connect the data so forecasts and risk signals are used inside the daily sales process.' },
  },
  'ai-governance': {
    ka: { eyebrow: 'AI უსაფრთხოება', title: 'AI დანერგვა, რომელსაც თქვენი კომპანია მართავს.', description: 'AI სისტემის სანდოობა იწყება წესებით: ვის აქვს წვდომა, რომელი მონაცემი გამოიყენება, როგორ იზომება პასუხის ხარისხი და როდის ერთვება ადამიანი გადაწყვეტილებაში.', outcomes: ['მონაცემისა და წვდომის პოლიტიკა', 'ხარისხისა და რისკის კონტროლი', 'ადამიანის დამტკიცების წესები'], outcomeDescriptions: ['სისტემის მონაცემთა საზღვრები და უფლებები წინასწარ არის გაწერილი.', 'ხარისხი, გამონაკლისები და რისკები წარმოებაში მუდმივად მოწმდება.', 'მაღალი რისკის შემთხვევა პასუხისმგებელ ადამიანთან ბრუნდება.'], steps: ['რისკისა და მონაცემის შეფასება', 'პოლიტიკისა და კონტროლის დიზაინი', 'მონიტორინგი და გაუმჯობესება'], implementationTitle: 'უსაფრთხოება დანერგვის ცალკე ფენა არ არის.', implementationDescription: 'წვდომა, შეფასება, fallback და ადამიანის ჩართულობა სისტემის დიზაინიდანვე განისაზღვრება.' },
    en: { eyebrow: 'AI SAFETY', title: 'Deploy AI your company can govern.', description: 'Trustworthy AI starts with rules: who can access it, which data it can use, how quality is measured, and when a person must decide.', outcomes: ['Data and access policy', 'Quality and risk controls', 'Human approval rules'], outcomeDescriptions: ['Data boundaries and permissions are explicit before deployment.', 'Quality, exceptions, and risk are continuously checked in production.', 'High-risk cases return to an accountable person.'], steps: ['Assess risk and data', 'Design policy and controls', 'Monitor and improve'], implementationTitle: 'Safety is not a separate deployment layer.', implementationDescription: 'Access, evaluation, fallback, and human involvement are defined as part of the system design.' },
  },
};

export async function generateMetadata({ params }: { params: Promise<{ locale: string; slug: string }> }): Promise<Metadata> {
  const { locale, slug } = await params;
  const content = serviceCopy[slug];
  if (!content) return { title: locale === 'en' ? 'Service not found' : 'სერვისი ვერ მოიძებნა', robots: { index: false, follow: false } };
  return localizedMetadata({ locale, path: `/services/${slug}`, title: { ka: content.ka.title, en: content.en.title }, description: { ka: content.ka.description, en: content.en.description } });
}

export default async function ServiceDetailPage({ params }: { params: Promise<{ locale: string; slug: string }> }) {
  const { locale, slug } = await params;
  setRequestLocale(locale);
  const content = serviceCopy[slug]?.[locale === 'en' ? 'en' : 'ka'];
  if (!content) notFound();
  const english = locale === 'en';
  const items = content.outcomes.map((title, index) => ({ title, text: content.outcomeDescriptions[index] }));
  return <div className="relative overflow-hidden pt-32 pb-24"><BreadcrumbStructuredData locale={locale} items={[{ name: english ? 'Home' : 'მთავარი', path: '' }, { name: english ? 'Services' : 'სერვისები', path: '/services' }, { name: content.title, path: `/services/${slug}` }]} /><div className="ai-grid pointer-events-none absolute inset-0 -z-10 opacity-40"/><section className="mx-auto max-w-5xl px-6 lg:px-8"><p className="text-xs font-bold tracking-[.2em] text-cyan-700 dark:text-cyan-300">{content.eyebrow}</p><h1 className="mt-5 max-w-4xl text-4xl font-bold leading-tight text-slate-950 dark:text-white sm:text-6xl">{content.title}</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-slate-600 dark:text-slate-300">{content.description}</p><div className="mt-10 flex flex-wrap gap-3"><Link href="/consultation" className="inline-flex items-center gap-2 rounded-xl bg-slate-950 px-6 py-4 text-sm font-bold text-white dark:bg-white dark:text-slate-950">{english ? 'Start with a consultation' : 'დაიწყეთ კონსულტაციით'} <ArrowUpRight size={18}/></Link><Link href="/projects" className="inline-flex items-center gap-2 rounded-xl border border-slate-900/15 px-6 py-4 text-sm font-bold text-slate-950 dark:border-white/15 dark:text-white">{english ? 'View products and projects' : 'ნახეთ ჩვენი პროდუქტები'}</Link></div></section><section className="mx-auto mt-20 grid max-w-5xl gap-5 px-6 md:grid-cols-3 lg:px-8">{items.map(({ title, text }, index) => { const Icon = [MessageSquareText, Network, LockKeyhole][index]; return <div key={title} className="glass-panel rounded-3xl p-6"><Icon size={23} className="text-cyan-700 dark:text-cyan-200"/><h2 className="mt-8 text-lg font-bold text-slate-950 dark:text-white">{title}</h2><p className="mt-3 text-sm leading-7 text-slate-600 dark:text-slate-300">{text}</p></div>})}</section><section className="mx-auto mt-20 max-w-5xl px-6 lg:px-8"><div className="glass-panel rounded-[2rem] p-8 sm:p-10"><Sparkles className="text-primary"/><h2 className="mt-5 text-2xl font-bold text-slate-950 dark:text-white">{content.implementationTitle}</h2><p className="mt-4 max-w-3xl leading-8 text-slate-600 dark:text-slate-300">{content.implementationDescription}</p><div className="mt-7 grid gap-4 md:grid-cols-3">{content.steps.map((step, index) => <div key={step} className="rounded-2xl border border-slate-900/10 p-4 dark:border-white/10"><span className="text-xs font-bold text-primary">0{index + 1}</span><p className="mt-3 text-sm font-bold text-slate-950 dark:text-white">{step}</p></div>)}</div></div></section></div>;
}
