import type { Metadata } from 'next';
import { ArrowUpRight, CircleDashed } from 'lucide-react';
import { setRequestLocale } from 'next-intl/server';
import { Link } from '@/i18n/routing';
import BreadcrumbStructuredData from '@/components/BreadcrumbStructuredData';
import { localizedMetadata } from '@/lib/seo/metadata';

const copy = {
  ka: { eyebrow: 'AI READINESS / SELF-ASSESSMENT', title: 'არის თუ არა თქვენი ბიზნესი მზად AI სისტემის დასანერგად?', description: 'AI readiness არ ნიშნავს, რომ უკვე დიდი მონაცემთა გუნდი გყავთ. ნიშნავს, რომ შეგიძლიათ იპოვოთ კონკრეტული პროცესი, პასუხისმგებელი ადამიანი და გაზომვადი შედეგი.', questionTitle: 'ხუთი კითხვა პირველ პილოტამდე', checks: [['პროცესი', 'არსებობს განმეორებადი სამუშაო პროცესი, რომელსაც დღეს გუნდი ხელით მართავს?'], ['მონაცემები', 'ცოდნა, დოკუმენტები ან CRM ჩანაწერები საკმარისად ორგანიზებულია?'], ['Ownership', 'ვინ ამოწმებს AI-ის პასუხს და მართავს პროცესის ხარისხს?'], ['ინტეგრაცია', 'რომელი სისტემები უნდა დაუკავშირდეს პირველ პილოტს?'], ['შედეგი', 'როგორ გაზომავთ დროს, ხარისხს, კონვერსიას ან დანახარჯს?']], asideTitle: 'თუ სამზე მეტ კითხვაზე “კი” პასუხობთ, პილოტი რეალისტურია.', asideText: 'შემდეგი ნაბიჯი არის readiness workshop: ვირჩევთ use case-ს, ვადგენთ data boundary-ს და ვქმნით delivery plan-ს.', cta: 'დაგეგმეთ readiness workshop', secondary: 'ნახეთ დანერგვის მოდელი' },
  en: { eyebrow: 'AI READINESS / SELF-ASSESSMENT', title: 'Is your business ready to deploy an AI system?', description: 'AI readiness does not require a large data team. It means you can identify a specific process, an accountable owner, and a measurable outcome.', questionTitle: 'Five questions before the first pilot', checks: [['Process', 'Is there a repeatable workflow the team currently manages by hand?'], ['Data', 'Are the knowledge, documents, or CRM records organized enough to use?'], ['Ownership', 'Who reviews the AI response and owns process quality?'], ['Integration', 'Which systems need to connect to the first pilot?'], ['Outcome', 'How will you measure time, quality, conversion, or cost?']], asideTitle: 'If you can answer yes to more than three, a pilot may be realistic.', asideText: 'The next step is a readiness workshop: choose a use case, set the data boundary, and create a delivery plan.', cta: 'Plan a readiness workshop', secondary: 'See the delivery model' },
} as const;

export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> {
  const { locale } = await params;
  return localizedMetadata({ locale, path: '/ai-readiness', title: { ka: 'AI მზადყოფნის შეფასება', en: 'AI readiness assessment' }, description: { ka: copy.ka.description, en: copy.en.description } });
}

export default async function AiReadinessPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  setRequestLocale(locale);
  const language = locale === 'en' ? 'en' : 'ka';
  const text = copy[language];
  return <div className="relative overflow-hidden pt-32 pb-24"><BreadcrumbStructuredData locale={language} items={[{ name: language === 'en' ? 'Home' : 'მთავარი', path: '' }, { name: 'AI Readiness', path: '/ai-readiness' }]} /><div className="ai-grid pointer-events-none absolute inset-0 -z-10 opacity-40"/><section className="mx-auto max-w-6xl px-6 lg:px-8"><p className="text-xs font-bold tracking-[.2em] text-primary">{text.eyebrow}</p><h1 className="mt-5 max-w-4xl text-4xl font-bold leading-tight text-slate-950 dark:text-white sm:text-6xl">{text.title}</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-slate-600 dark:text-slate-300">{text.description}</p><div className="mt-14 grid gap-5 lg:grid-cols-[1fr_.7fr]"><div className="glass-panel rounded-[2rem] p-7 sm:p-9"><p className="text-sm font-bold text-slate-950 dark:text-white">{text.questionTitle}</p><div className="mt-7 space-y-4">{text.checks.map(([title, description], index) => <div key={title} className="flex gap-4 rounded-2xl border border-slate-900/10 bg-white/50 p-4 dark:border-white/10 dark:bg-black/10"><span className="flex size-7 shrink-0 items-center justify-center rounded-full bg-primary/15 text-xs font-bold text-primary">{index + 1}</span><div><h2 className="font-bold text-slate-950 dark:text-white">{title}</h2><p className="mt-1 text-sm leading-6 text-slate-600 dark:text-slate-300">{description}</p></div></div>)}</div></div><aside className="rounded-[2rem] bg-slate-950 p-7 text-white sm:p-9"><CircleDashed className="text-cyan-300" size={27}/><h2 className="mt-8 text-2xl font-bold">{text.asideTitle}</h2><p className="mt-5 text-sm leading-7 text-slate-300">{text.asideText}</p><Link href="/consultation" className="mt-8 inline-flex items-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-bold text-slate-950">{text.cta} <ArrowUpRight size={17}/></Link><Link href="/implementation" className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-cyan-200">{text.secondary} <ArrowUpRight size={17}/></Link></aside></div></section></div>;
}
