import type { Metadata } from 'next';
import { ArrowUpRight, MessageCircle, Network, ShieldCheck } from 'lucide-react';
import { setRequestLocale } from 'next-intl/server';
import { Link } from '@/i18n/routing';
import BreadcrumbStructuredData from '@/components/BreadcrumbStructuredData';
import RoiCalculator from '@/components/RoiCalculator';
import { localizedMetadata } from '@/lib/seo/metadata';

const copy = {
  ka: { eyebrow: 'AI OPERATOR / ბიზნესის სამუშაო ფენა', title: 'AI ოპერატორი, რომელიც მოთხოვნას პასუხიდან მოქმედებამდე მიჰყვება.', description: 'AI Operator არის კორპორაციული AI ფენა მომხმარებლის მხარდაჭერისთვის, გაყიდვებისთვის და განმეორებადი ოპერაციებისთვის. ის მუშაობს თქვენს წესებთან, ცოდნასთან და CRM პროცესთან.', cta: 'დაგეგმეთ AI სესია', guide: 'უსაფრთხოების მიდგომა', steps: [['მიღება', 'იღებს მოთხოვნას ჩატიდან, ვებგვერდიდან ან ხმოვანი არხიდან.'], ['გაგება', 'პოულობს განზრახვას, საჭირო მონაცემს და კომპანიის შესაბამის ცოდნას.'], ['მოქმედება', 'ქმნის CRM ჩანაწერს, აგზავნის პასუხს ან რთულ შემთხვევას ადამიანს გადასცემს.']], features: [['მომხმარებლის მხარდაჭერა', 'პასუხები ქართულად და სწორ არხზე გადამისამართება.'], ['გაყიდვების ავტომატიზაცია', 'ლიდის კონტექსტი და შემდეგი საუკეთესო ნაბიჯი.'], ['კონტროლირებადი AI', 'წვდომა, შეფასება და human handoff თავიდანვე განსაზღვრულია.']], featureTitle: 'ერთი ოპერაციული ფენა სხვადასხვა გუნდს აერთიანებს.', roiTitle: 'შეაფასეთ ავტომატიზაციის პირველი ჰიპოთეზა.' },
  en: { eyebrow: 'AI OPERATOR / BUSINESS OPERATING LAYER', title: 'An AI operator that follows a request from answer to action.', description: 'AI Operator is an enterprise AI layer for customer support, sales, and repetitive operations. It works with your rules, knowledge, and CRM workflow.', cta: 'Plan an AI session', guide: 'Read the safety approach', steps: [['Receive', 'Accepts a request from chat, your website, or a voice channel.'], ['Understand', 'Finds intent, required data, and the relevant approved company knowledge.'], ['Act', 'Creates a CRM record, sends a response, or hands a complex case to a person.']], features: [['Customer support', 'Answer in the right language and route the request to the right channel.'], ['Sales automation', 'Preserve lead context and recommend the next best action.'], ['Governed AI', 'Access, evaluation, and human handoff are defined from the start.']], featureTitle: 'One operating layer connects different teams.', roiTitle: 'Estimate the first automation hypothesis.' },
} as const;

export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> {
  const { locale } = await params;
  return localizedMetadata({ locale, path: '/solutions/ai-operator', title: { ka: 'AI Operator ბიზნესისთვის', en: 'AI Operator for business' }, description: { ka: copy.ka.description, en: copy.en.description } });
}

export default async function AiOperatorPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  setRequestLocale(locale);
  const language = locale === 'en' ? 'en' : 'ka';
  const text = copy[language];
  return <main className="mx-auto max-w-7xl px-6 pb-24 pt-32 lg:px-8"><BreadcrumbStructuredData locale={language} items={[{ name: language === 'en' ? 'Home' : 'მთავარი', path: '' }, { name: 'AI Operator', path: '/solutions/ai-operator' }]} /><p className="font-heading text-xs font-bold tracking-[.16em] text-primary">{text.eyebrow}</p><h1 className="mt-5 max-w-4xl text-4xl font-semibold tracking-[-.05em] text-slate-950 dark:text-white sm:text-7xl">{text.title}</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-slate-600 dark:text-slate-300">{text.description}</p><div className="mt-10 flex flex-wrap gap-3"><Link href="/consultation" className="font-heading inline-flex items-center gap-2 rounded-full bg-black px-6 py-4 text-sm font-bold text-white dark:bg-white dark:text-black">{text.cta} <ArrowUpRight size={18}/></Link><Link href="/docs/ai-governance" className="font-heading inline-flex items-center gap-2 rounded-full border border-black/15 px-6 py-4 text-sm font-bold dark:border-white/15">{text.guide}</Link></div><section className="mt-20 grid gap-4 md:grid-cols-3">{text.steps.map(([title, description], index) => <article key={title} className="rounded-[1.75rem] border border-black/15 p-6 dark:border-white/15"><span className="font-heading text-xs font-bold text-neutral-500">0{index + 1}</span><h2 className="mt-12 text-xl font-semibold text-slate-950 dark:text-white">{title}</h2><p className="mt-3 leading-7 text-slate-600 dark:text-slate-300">{description}</p></article>)}</section><section className="mt-16"><h2 className="text-3xl font-semibold tracking-[-.04em] text-slate-950 dark:text-white">{text.featureTitle}</h2><div className="mt-8 grid gap-4 sm:grid-cols-3">{text.features.map(([title, description], index) => { const Icon = [MessageCircle, Network, ShieldCheck][index]; return <article key={title} className="rounded-[1.75rem] border border-black/15 p-6 dark:border-white/15"><Icon size={22}/><h3 className="mt-8 text-lg font-semibold text-slate-950 dark:text-white">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-600 dark:text-slate-300">{description}</p></article>; })}</div></section><section className="mt-16"><h2 className="mb-6 text-2xl font-semibold text-slate-950 dark:text-white">{text.roiTitle}</h2><RoiCalculator locale={language}/></section></main>;
}
