import type { Metadata } from 'next';
import { ArrowUpRight, Bot, Code2, Database, Headphones, ShieldCheck, UsersRound, Workflow } from 'lucide-react';
import { setRequestLocale } from 'next-intl/server';
import { Link } from '@/i18n/routing';
import { localizedMetadata } from '@/lib/seo/metadata';

export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> {
  const { locale } = await params;
  return localizedMetadata({ locale, path: '/services', title: { ka: 'AI სერვისები ბიზნესისთვის', en: 'AI services for business' }, description: { ka: 'ხმოვანი AI, RAG სისტემები, AI CRM ინტეგრაცია, გაყიდვების ავტომატიზაცია და AI-ზე დაფუძნებული ვებ-პროდუქტები საქართველოს ბიზნესებისთვის.', en: 'Voice AI, RAG systems, AI CRM integration, sales automation, and AI-native web products for businesses in Georgia.' } });
}

const services = [
  { href: '/services/ai-voice-agents', icon: Headphones, label: 'ხმოვანი AI', title: 'AI ხმოვანი ასისტენტები და ჩატბოტები', description: 'ქართულად მოსაუბრე ხმოვანი და ტექსტური ასისტენტები მომხმარებლის მხარდაჭერის, ლიდების კვალიფიკაციისა და ზარების ავტომატიზაციისთვის.', outputs: ['24/7 მხარდაჭერა', 'CRM კონტექსტის აღრიცხვა', 'ზარების გადამისამართება და ხარისხის კონტროლი'] },
  { href: '/services/rag-internal-ai', icon: Database, label: 'ცოდნის AI', title: 'RAG და შიდა AI სისტემები', description: 'ენის მოდელი, რომელიც უსაფრთხოდ მუშაობს თქვენს დოკუმენტებთან, წესებთან, CRM-სა და ცოდნის ბაზასთან.', outputs: ['როლებზე დაფუძნებული წვდომა', 'წყაროზე მიბმული პასუხები', 'შიდა პროცესების ავტომატიზაცია'] },
  { href: '/services/business-automation', icon: Workflow, label: 'ოპერაციული AI', title: 'ბიზნეს პროცესების ავტომატიზაცია', description: 'AI აგენტები, რომლებიც ამუშავებენ განმეორებად დავალებებს, აკონტროლებენ SLA-ს და ადამიანურ გუნდს რთულ ნაწილზე ტოვებენ.', outputs: ['ლიდების გადანაწილება', 'დოკუმენტების დამუშავება', 'ოპერაციული შეტყობინებები'] },
  { href: '/services/ai-native-web', icon: Code2, label: 'პროდუქტის ინჟინერია', title: 'AI-ზე დაფუძნებული ვებ-პროდუქტები', description: 'სწრაფი საიტები და ვებ-აპლიკაციები, სადაც AI ფუნქცია არქიტექტურის ორგანული ნაწილია და არა ზედაპირული დამატება.', outputs: ['კონვერსიაზე ორიენტირებული UX', 'დაცული backend პროცესები', 'წარმადობის მონიტორინგი'] },
  { href: '/services/ai-crm-integration', icon: UsersRound, label: 'AI CRM', title: 'AI CRM ინტეგრაცია და ოპტიმიზაცია', description: 'ვაშენებთ AI ფენას თქვენს არსებულ CRM-ში, რათა ლიდები ავტომატურად შეფასდეს, გაყიდვების გუნდი სწორ დროს მიიღებდეს სწორ კონტექსტს და მონაცემი მოქმედებად გადაიქცეს.', outputs: ['ლიდების შეფასება', 'შემდეგი ნაბიჯის რეკომენდაცია', 'CRM მონაცემის გამდიდრება'] },
  { href: '/services/ai-first-crm', icon: Workflow, label: 'CRM ტრანსფორმაცია', title: 'კომპანიის AI-first CRM-ზე გადაყვანა', description: 'თუ არსებული CRM ბიზნესს აღარ შეესაბამება, ვგეგმავთ გადასვლას, მონაცემის მიგრაციასა და ახალ AI-first ოპერაციულ მოდელს ისე, რომ გაყიდვები და მომსახურება არ გაჩერდეს.', outputs: ['CRM სტრატეგია და არქიტექტურა', 'მონაცემის უსაფრთხო მიგრაცია', 'AI პროცესები თავიდანვე'] },
  { href: '/services/sales-intelligence', icon: Database, label: 'გაყიდვების ინტელექტი', title: 'AI გაყიდვების ინტელექტი და პროგნოზირება', description: 'AI აერთიანებს ლიდების, ზარების, წერილებისა და CRM მონაცემს, რათა გაყიდვების გუნდმა სწრაფად დაინახოს პრიორიტეტი, რისკი და მომდევნო საუკეთესო მოქმედება.', outputs: ['გაყიდვების პროგნოზი', 'გარიგების რისკის სიგნალები', 'მომდევნო ნაბიჯის რეკომენდაცია'] },
  { href: '/services/ai-governance', icon: ShieldCheck, label: 'AI უსაფრთხოება', title: 'AI Governance და უსაფრთხო დანერგვა', description: 'ვადგენთ მონაცემის, წვდომის, ხარისხის შემოწმებისა და ადამიანის კონტროლის წესებს, რათა AI სისტემები წარმოებაში მართვადი და უსაფრთხო იყოს.', outputs: ['წვდომისა და მონაცემის წესები', 'ხარისხის მონიტორინგი', 'ადამიანის დამტკიცების ეტაპები'] },
];
const englishServices = [
  { href: '/services/ai-voice-agents', icon: Headphones, label: 'VOICE AI', title: 'AI voice assistants and chatbots', description: 'Natural voice and text assistants for customer support, lead qualification, and call automation.', outputs: ['24/7 support', 'CRM context capture', 'Call routing and quality control'] },
  { href: '/services/rag-internal-ai', icon: Database, label: 'KNOWLEDGE AI', title: 'RAG and internal AI systems', description: 'Language models that work securely with your documents, rules, CRM, and internal knowledge base.', outputs: ['Role-based access', 'Source-grounded answers', 'Internal workflow automation'] },
  { href: '/services/business-automation', icon: Workflow, label: 'OPERATIONS AI', title: 'Business process automation', description: 'AI agents handle repetitive work, monitor service levels, and return complex cases to your team.', outputs: ['Lead routing', 'Document processing', 'Operational alerts'] },
  { href: '/services/ai-native-web', icon: Code2, label: 'PRODUCT ENGINEERING', title: 'AI-native web products', description: 'Fast websites and web applications where AI is part of the architecture, not a surface-level add-on.', outputs: ['Conversion-focused UX', 'Secure backend workflows', 'Performance monitoring'] },
  { href: '/services/ai-crm-integration', icon: UsersRound, label: 'AI CRM', title: 'AI CRM integration and optimization', description: 'We add an AI layer to your existing CRM so leads are scored, context is captured, and the next action becomes clear.', outputs: ['Lead scoring', 'Next-action recommendations', 'CRM enrichment'] },
  { href: '/services/ai-first-crm', icon: Workflow, label: 'CRM TRANSFORMATION', title: 'Move your company to an AI-first CRM model', description: 'We plan migration, data quality, and new AI workflows without stopping sales or customer service operations.', outputs: ['CRM strategy and architecture', 'Safe data migration', 'AI workflows from day one'] },
  { href: '/services/sales-intelligence', icon: Database, label: 'SALES INTELLIGENCE', title: 'AI sales intelligence and forecasting', description: 'AI combines lead, call, message, and CRM signals so teams can see priority, risk, and the next best action.', outputs: ['Sales forecasting', 'Deal risk signals', 'Next-best-action recommendations'] },
  { href: '/services/ai-governance', icon: ShieldCheck, label: 'AI SAFETY', title: 'AI governance and safe deployment', description: 'We define data, access, quality, and human-control rules so AI remains manageable in production.', outputs: ['Data and access policies', 'Quality monitoring', 'Human approval points'] },
];

export default async function ServicesPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  setRequestLocale(locale);
  const english = locale === 'en';
  const activeServices = english ? englishServices : services;
  return <div className="relative overflow-hidden pt-32 pb-24"><div className="ai-grid pointer-events-none absolute inset-0 -z-10 opacity-40" />
    <section className="mx-auto max-w-7xl px-6 lg:px-8"><p className="text-xs font-bold tracking-[.2em] text-primary">{english ? 'IMI.GE CAPABILITIES' : 'IMI.GE შესაძლებლობები'}</p><h1 className="mt-5 max-w-4xl text-4xl font-bold leading-tight text-slate-950 dark:text-white sm:text-6xl">{english ? 'AI services that become part of your operating system.' : 'AI სერვისები, რომლებიც თქვენს ოპერაციულ სისტემაში ერთიანდება.'}</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-slate-600 dark:text-slate-300">{english ? 'We work from a specific business problem, not a technology demo. Every engagement starts with diagnosis and ends with a measurable, secure production system.' : 'ვმუშაობთ კონკრეტული ბიზნეს-ამოცანით და არა ტექნოლოგიის დემონსტრირებით. ყოველი მიმართულება იწყება პროცესის დიაგნოსტიკით და სრულდება გაზომვადი, უსაფრთხო სისტემით.'}</p></section>
    <section className="mx-auto mt-16 grid max-w-7xl gap-5 px-6 lg:grid-cols-2 lg:px-8">{activeServices.map(({ href, icon: Icon, label, title, description, outputs }) => <article key={href} className="glass-panel rounded-[2rem] p-7 sm:p-9"><div className="flex items-start justify-between gap-6"><div className="flex size-12 items-center justify-center rounded-2xl bg-primary/15 text-primary"><Icon size={25}/></div><p className="text-[11px] font-bold tracking-[.16em] text-primary">{label}</p></div><h2 className="mt-10 text-2xl font-bold text-slate-950 dark:text-white">{title}</h2><p className="mt-4 text-sm leading-7 text-slate-600 dark:text-slate-300">{description}</p><div className="mt-8 grid gap-2 sm:grid-cols-3">{outputs.map((output) => <span key={output} className="rounded-xl border border-slate-900/10 bg-white/40 px-3 py-2 text-xs text-slate-600 dark:border-white/10 dark:bg-black/10 dark:text-slate-300">{output}</span>)}</div><Link href={href} className="mt-8 inline-flex items-center gap-2 text-sm font-bold text-slate-950 hover:text-primary dark:text-white">{english ? 'View service details' : 'სერვისის დეტალები'} <ArrowUpRight size={17}/></Link></article>)}</section>
    <section className="mx-auto mt-20 max-w-7xl px-6 lg:px-8"><div className="rounded-[2rem] border border-primary/25 bg-primary/10 p-8 sm:p-12"><Bot className="text-primary"/><h2 className="mt-6 text-3xl font-bold text-slate-950 dark:text-white">{english ? 'Not sure where to start?' : 'არ იცით, საიდან დაიწყოთ?'}</h2><p className="mt-4 max-w-2xl text-slate-600 dark:text-slate-300">{english ? 'In the first session we identify the workflow that can create value fastest, the data it needs, and how to avoid unnecessary AI experiments.' : 'საწყის შეხვედრაზე ვადგენთ, რომელი სამუშაო პროცესი მოიტანს სწრაფ შედეგს, რა მონაცემებია საჭირო და როგორ ავიცილოთ თავიდან არასაჭირო AI ექსპერიმენტები.'}</p><Link href="/consultation" className="mt-8 inline-flex items-center gap-2 rounded-xl bg-slate-950 px-6 py-4 text-sm font-bold text-white dark:bg-white dark:text-slate-950">{english ? 'Plan your AI strategy' : 'დაგეგმეთ AI სტრატეგია'} <ArrowUpRight size={18}/></Link></div></section>
  </div>;
}
