import type { Metadata } from 'next';
import { ArrowRight, ArrowUpRight, Bot, Code2, Database, Headphones, ShieldCheck, UsersRound, Workflow } from 'lucide-react';
import { setRequestLocale } from 'next-intl/server';
import { Link } from '@/i18n/routing';
import { localizedMetadata } from '@/lib/seo/metadata';

export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> {
  const { locale } = await params;
  return localizedMetadata({ locale, path: '/services', title: { ka: 'AI სერვისები ბიზნესისთვის', en: 'AI services for business' }, description: { ka: 'ხმოვანი AI, RAG სისტემები, AI CRM ინტეგრაცია, გაყიდვების ავტომატიზაცია და AI-ზე დაფუძნებული ვებ-პროდუქტები საქართველოს ბიზნესებისთვის.', en: 'Voice AI, RAG systems, AI CRM integration, sales automation, and AI-native web products for businesses in Georgia.' } });
}

const services = [
  { href: '/services/ai-voice-agents', icon: Headphones, label: 'ხმოვანი AI', title: 'AI ხმოვანი ასისტენტები და ჩატბოტები', description: 'ქართულად მოსაუბრე ხმოვანი და ტექსტური ასისტენტები მომხმარებლის მხარდაჭერის, ლიდების კვალიფიკაციისა და ზარების ავტომატიზაციისთვის.', outputs: ['24/7 მხარდაჭერა', 'CRM კონტექსტის აღრიცხვა', 'ზარების გადამისამართება და ხარისხის კონტროლი'] },
  { href: '/services/rag-internal-ai', icon: Database, label: 'ცოდნის AI', title: 'RAG და შიდა AI სისტემები', description: 'ენის მოდელი, რომელიც უსაფრთხოდ მუშაობს თქვენს დოკუმენტებთან, წესებთან, CRM-სა და ცოდნის ბაზასთან.', outputs: ['როლებზე დაფუძნებული წვდომა', 'წყაროზე მიბმული პასუხები', 'შიდა პროცესების ავტომატიზაცია'] },
  { href: '/services/business-automation', icon: Workflow, label: 'ოპერაციული AI', title: 'ბიზნეს პროცესების ავტომატიზაცია', description: 'AI აგენტები, რომლებიც ამუშავებენ განმეორებად დავალებებს, აკონტროლებენ SLA-ს და ადამიანურ გუნდს რთულ ნაწილზე ტოვებენ.', outputs: ['ლიდების გადანაწილება', 'დოკუმენტების დამუშავება', 'ოპერაციული შეტყობინებები'] },
  { href: '/services/ai-native-web', icon: Code2, label: 'პროდუქტის ინჟინერია', title: 'AI-ზე დაფუძნებული ვებ-პროდუქტები', description: 'სწრაფი საიტები და ვებ-აპლიკაციები, სადაც AI ფუნქცია არქიტექტურის ორგანული ნაწილია და არა ზედაპირული დამატება.', outputs: ['კონვერსიაზე ორიენტირებული UX', 'დაცული backend პროცესები', 'წარმადობის მონიტორინგი'] },
  { href: '/services/ai-crm-integration', icon: UsersRound, label: 'AI CRM', title: 'AI CRM ინტეგრაცია და ოპტიმიზაცია', description: 'ვაშენებთ AI ფენას თქვენს არსებულ CRM-ში, რათა ლიდები ავტომატურად შეფასდეს, გაყიდვების გუნდი სწორ დროს მიიღებდეს სწორ კონტექსტს და მონაცემი მოქმედებად გადაიქცეს.', outputs: ['ლიდების შეფასება', 'შემდეგი ნაბიჯის რეკომენდაცია', 'CRM მონაცემის გამდიდრება'] },
  { href: '/services/ai-first-crm', icon: Workflow, label: 'CRM ტრანსფორმაცია', title: 'კომპანიის AI-first CRM-ზე გადაყვანა', description: 'თუ არსებული CRM ბიზნესს აღარ შეესაბამება, ვგეგმავთ გადასვლას, მონაცემის მიგრაციასა და ახალ AI-first ოპერაციულ მოდელს ისე, რომ გაყიდვები და მომსახურება არ გაჩერდეს.', outputs: ['CRM სტრატეგია და არქიტექტურა', 'მონაცემის უსაფრთხო მიგრაცია', 'AI პროცესები თავიდანვე'] },
  { href: '/services/sales-intelligence', icon: Database, label: 'გაყიდვების ინტელექტი', title: 'AI გაყიდვების ინტელექტი და პროგნოზირება', description: 'AI აერთიანებს ლიდების, ზარების, წერილებისა და CRM მონაცემს, რათა გაყიდვების გუნდმა სწრაფად დაინახოს პრიორიტეტი, რისკი და მომდევნო საუკეთესო მოქმედება.', outputs: ['გაყიდვების პროგნოზი', 'გარიგების რისკის სიგნალები', 'მომდევნო ნაბიჯის რეკომენდაცია'] },
  { href: '/services/ai-governance', icon: ShieldCheck, label: 'AI უსაფრთხოება', title: 'AI Governance და უსაფრთხო დანერგვა', description: 'ვადგენთ მონაცემის, წვდომის, ხარისხის შემოწმებისა და ადამიანის კონტროლის წესებს, რათა AI სისტემები წარმოებაში მართვადი და უსაფრთხო იყოს.', outputs: ['წვდომისა და მონაცემის წესები', 'ხარისხის მონიტორინგი', 'ადამიანის დამტკიცების ეტაპები'] },
];
const englishServices = [
  { href: '/services/ai-voice-agents', icon: Headphones, label: 'VOICE AI', title: 'AI voice assistants and chatbots', description: 'Natural voice and text assistants for customer support, lead qualification, and call automation.', outputs: ['24/7 support', 'CRM context capture', 'Call routing and quality control'] },
  { href: '/services/rag-internal-ai', icon: Database, label: 'KNOWLEDGE AI', title: 'RAG and internal AI systems', description: 'Language models that work securely with your documents, rules, CRM, and internal knowledge base.', outputs: ['Role-based access', 'Source-grounded answers', 'Internal workflow automation'] },
  { href: '/services/business-automation', icon: Workflow, label: 'OPERATIONS AI', title: 'Business process automation', description: 'AI agents handle repetitive work, monitor service levels, and return complex cases to your team.', outputs: ['Lead routing', 'Document processing', 'Operational alerts'] },
  { href: '/services/ai-native-web', icon: Code2, label: 'PRODUCT ENGINEERING', title: 'AI-native web products', description: 'Fast websites and web applications where AI is part of the architecture, not a surface-level add-on.', outputs: ['Conversion-focused UX', 'Secure backend workflows', 'Performance monitoring'] },
  { href: '/services/ai-crm-integration', icon: UsersRound, label: 'AI CRM', title: 'AI CRM integration and optimization', description: 'We add an AI layer to your existing CRM so leads are scored, context is captured, and the next action becomes clear.', outputs: ['Lead scoring', 'Next-action recommendations', 'CRM enrichment'] },
  { href: '/services/ai-first-crm', icon: Workflow, label: 'CRM TRANSFORMATION', title: 'Move your company to an AI-first CRM model', description: 'We plan migration, data quality, and new AI workflows without stopping sales or customer service operations.', outputs: ['CRM strategy and architecture', 'Safe data migration', 'AI workflows from day one'] },
  { href: '/services/sales-intelligence', icon: Database, label: 'SALES INTELLIGENCE', title: 'AI sales intelligence and forecasting', description: 'AI combines lead, call, message, and CRM signals so teams can see priority, risk, and the next best action.', outputs: ['Sales forecasting', 'Deal risk signals', 'Next-best-action recommendations'] },
  { href: '/services/ai-governance', icon: ShieldCheck, label: 'AI SAFETY', title: 'AI governance and safe deployment', description: 'We define data, access, quality, and human-control rules so AI remains manageable in production.', outputs: ['Data and access policies', 'Quality monitoring', 'Human approval points'] },
];

export default async function ServicesPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  setRequestLocale(locale);
  const english = locale === 'en';
  const activeServices = english ? englishServices : services;
  return <main className="services-experience">
    <section className="services-hero">
      <div className="services-container services-hero__grid">
        <div className="services-hero__intro"><div className="page-kicker"><span className="signal-dot" />{english ? 'IMI.GE / CAPABILITY MAP' : 'IMI.GE / შესაძლებლობების რუკა'}</div><h1>{english ? <>AI systems for the work <em>behind</em> the business.</> : <>AI სისტემები იმ სამუშაოსთვის, რაც ბიზნესს <em>ამოძრავებს.</em></>}</h1><p>{english ? 'We start with one business signal, design the workflow around it, and ship a secure system your team can actually operate.' : 'ვიწყებთ ერთი ბიზნეს-სიგნალით, მის გარშემო ვაწყობთ workflow-ს და ვქმნით უსაფრთხო სისტემას, რომელსაც თქვენი გუნდი რეალურად მართავს.'}</p><div className="services-hero__actions"><Link href="/consultation" className="signal-button signal-button--solid">{english ? 'Map a workflow' : 'დახაზეთ workflow'} <ArrowUpRight size={16} /></Link><Link href="/projects" className="signal-button signal-button--quiet">{english ? 'See products' : 'ნახეთ პროდუქტები'} <ArrowRight size={16} /></Link></div></div>
        <div className="services-hero__board" aria-label={english ? 'IMI.GE service operating board' : 'IMI.GE სერვისების ოპერაციული დაფა'}><div className="services-hero__board-head"><span>{english ? 'DELIVERY BOARD' : 'დანერგვის დაფა'}</span><span className="board-status"><i />{english ? 'Accepting briefs' : 'ახალი ამოცანები ღიაა'}</span></div><div className="services-hero__board-body"><div className="board-stat"><strong>08</strong><span>{english ? 'systems ready to configure' : 'სისტემა კონფიგურაციისთვის'}</span></div><div className="board-stat"><strong>03</strong><span>{english ? 'layers in every pilot' : 'ფენა ყოველ პილოტში'}</span></div><div className="board-stat"><strong>01</strong><span>{english ? 'clear next action' : 'მკაფიო შემდეგი ნაბიჯი'}</span></div></div><div className="services-hero__board-flow"><span className="board-flow-node board-flow-node--muted">{english ? 'Business signal' : 'ბიზნეს-სიგნალი'}</span><ArrowRight size={15} /><span className="board-flow-node board-flow-node--active">{english ? 'IMI workflow' : 'IMI workflow'}</span><ArrowRight size={15} /><span className="board-flow-node">{english ? 'Measured result' : 'გაზომვადი შედეგი'}</span></div></div>
      </div>
    </section>
    <section className="services-catalog services-container"><div className="services-catalog__head"><div><p className="page-kicker">{english ? 'THE SERVICE LAYER' : 'სერვისების ფენა'}</p><h2>{english ? 'Choose the layer your operation is missing.' : 'აირჩიეთ ფენა, რომელიც თქვენს ოპერაციას აკლია.'}</h2></div><p>{english ? 'Each capability is a system surface, not a standalone feature. Combine the pieces around the work you need to move.' : 'თითოეული შესაძლებლობა ცალკე ფუნქცია კი არა, სისტემის ზედაპირია. ვაერთიანებთ იმ ნაწილებს, რომლებიც თქვენს სამუშაოს სჭირდება.'}</p></div><div className="services-grid">{activeServices.map(({ href, icon: Icon, label, title, description, outputs }, index) => <article key={href} className="service-card"><div className="service-card__head"><span className="service-card__index">{String(index + 1).padStart(2, '0')}</span><span className="service-card__icon"><Icon size={20} /></span><span className="service-card__label">{label}</span></div><h3>{title}</h3><p className="service-card__description">{description}</p><div className="service-card__outputs">{outputs.map((output) => <span key={output}><span className="output-check" />{output}</span>)}</div><Link href={href} className="service-card__link">{english ? 'Open capability' : 'შესაძლებლობის ნახვა'} <ArrowUpRight size={16} /></Link></article>)}</div></section>
    <section className="services-cta services-container"><div className="services-cta__signal"><Bot size={21} /><span>{english ? 'FIRST SIGNAL / HUMAN-LED' : 'პირველი სიგნალი / ადამიანის კონტროლი'}</span></div><div><h2>{english ? 'Not sure which workflow to start with?' : 'არ იცით, რომელი workflow-ით დაიწყოთ?'}</h2><p>{english ? 'In one focused session we identify the highest-value process, its data boundaries, and the smallest pilot that can prove it.' : 'ერთ ფოკუსირებულ შეხვედრაში ვპოულობთ ყველაზე ღირებულ პროცესს, მონაცემის საზღვრებსა და უმცირეს პილოტს, რომელიც შედეგს დაამტკიცებს.'}</p></div><Link href="/consultation" className="signal-button signal-button--light">{english ? 'Plan the first step' : 'დაგეგმეთ პირველი ნაბიჯი'} <ArrowUpRight size={16} /></Link></section>
  </main>;
}
