import type { Metadata } from 'next';
import { ArrowUpRight, Bot, Braces, Check, Database, Headphones, Orbit, ShieldCheck, Sparkles, Workflow } from 'lucide-react';
import { setRequestLocale } from 'next-intl/server';
import { Link } from '@/i18n/routing';
import FAQStructuredData from '@/components/FAQStructuredData';

export const metadata: Metadata = {
  title: 'AI სისტემები ბიზნესისთვის საქართველოში',
  description: 'IMI.GE ქმნის ხმოვან AI ასისტენტებს, RAG სისტემებს, CRM ავტომატიზაციასა და AI-ზე დაფუძნებულ ვებ-პროდუქტებს საქართველოს კომპანიებისთვის.',
};

const questions = [
  { question: 'რით იწყება AI ინტეგრაცია ბიზნესში?', answer: 'პირველი ნაბიჯია კონკრეტული პროცესის, მონაცემების, მომხმარებლის გზისა და მოსალოდნელი შედეგის შეფასება. მხოლოდ ამის შემდეგ ვარჩევთ მოდელსა და ინტეგრაციის არქიტექტურას.' },
  { question: 'შეუძლია AI-ს ქართულად მუშაობა?', answer: 'დიახ. ხმოვანი, ტექსტური და ცოდნის სისტემები შეიძლება მოერგოს ქართულ ენას, თქვენს ტერმინოლოგიასა და ბრენდის კომუნიკაციის ტონს.' },
  { question: 'როგორ იცავთ კომპანიის მონაცემებს?', answer: 'არქიტექტურა იწყება მონაცემთა კლასიფიკაციით, წვდომის კონტროლით, წყაროზე მიბმული პასუხებით და უსაფრთხო ინტეგრაციების შერჩევით.' },
];

const flow = [
  ['01', 'მომხმარებლის მოთხოვნა', 'ზარი, ჩატი ან შიდა დავალება იწყებს პროცესს.'],
  ['02', 'AI და ცოდნის ფენა', 'სისტემა პოულობს კონტექსტს და ამზადებს დასაბუთებულ პასუხს.'],
  ['03', 'შიდა სისტემები', 'CRM, ERP და სამუშაო პროცესები იღებს საჭირო მოქმედებას.'],
  ['04', 'ადამიანის კონტროლი', 'გუნდი ამოწმებს გამონაკლისს და მართავს ხარისხს.'],
];

const capabilities = [
  [Headphones, 'მომხმარებლის ხმა', 'ზარი, ჩატი და მოთხოვნა რჩება ერთ კონტექსტში.'],
  [Database, 'ცოდნა მოქმედებაში', 'დოკუმენტი და მონაცემი ხდება პასუხის დასაბუთებული წყარო.'],
  [Workflow, 'ნაკლები ხელით შესრულებული სამუშაო', 'აგენტები ასრულებს წესზე დაფუძნებულ განმეორებად ნაბიჯებს.'],
  [Braces, 'პროდუქტი როგორც უპირატესობა', 'AI ფუნქცია თავიდანვე ჩაშენებულია გამოცდილებასა და backend-ში.'],
] as const;

export default async function HomePage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  setRequestLocale(locale);
  return <main className="overflow-hidden"><FAQStructuredData items={questions}/>
    <section className="relative isolate min-h-[820px] overflow-hidden pt-32"><div className="ai-grid absolute inset-0 -z-20 opacity-50"/><div className="absolute left-[8%] top-28 -z-10 size-[34rem] rounded-full bg-primary/25 blur-[120px]"/><div className="absolute right-[4%] top-56 -z-10 size-[26rem] rounded-full bg-cyan-400/15 blur-[110px]"/>
      <div className="mx-auto grid max-w-7xl gap-14 px-6 pb-20 lg:grid-cols-[1.1fr_.9fr] lg:px-8"><div className="py-16 lg:py-24"><p className="inline-flex items-center gap-2 rounded-full border border-slate-900/10 bg-white/65 px-4 py-2 text-[11px] font-bold tracking-[.18em] text-slate-700 shadow-sm dark:border-cyan-300/20 dark:bg-cyan-300/10 dark:text-cyan-200"><Sparkles size={14}/> AI სისტემები / საქართველო / 2026</p><h1 className="mt-8 max-w-4xl text-5xl font-bold leading-[.98] tracking-[-.045em] text-slate-950 dark:text-white sm:text-7xl xl:text-8xl">არ დააყენოთ უბრალოდ AI.<span className="block bg-gradient-to-r from-primary via-fuchsia-500 to-cyan-500 bg-clip-text text-transparent">ააწყეთ ახალი ოპერაციული სისტემა.</span></h1><p className="mt-8 max-w-2xl text-lg leading-8 text-slate-600 dark:text-slate-300">IMI.GE აერთიანებს ხმოვან AI-ს, კორპორაციულ ცოდნასა და ავტომატიზაციას ერთ სამუშაო არქიტექტურაში, რომ მომხმარებლის მოთხოვნა რეალურ გადაწყვეტილებად გადაიქცეს.</p><div className="mt-10 flex flex-col gap-3 sm:flex-row"><Link href="/consultation" className="group inline-flex items-center justify-center gap-3 rounded-2xl bg-slate-950 px-6 py-4 text-sm font-bold text-white transition hover:-translate-y-0.5 hover:bg-primary dark:bg-white dark:text-slate-950">AI სტრატეგიის კონსულტაცია <ArrowUpRight size={18}/></Link><Link href="/ai-readiness" className="inline-flex items-center justify-center rounded-2xl border border-slate-900/15 bg-white/50 px-6 py-4 text-sm font-bold text-slate-950 dark:border-white/15 dark:bg-white/5 dark:text-white">შეაფასეთ AI მზადყოფნა</Link></div><div className="mt-12 flex flex-wrap gap-x-7 gap-y-3 text-sm text-slate-600 dark:text-slate-300"><span className="flex items-center gap-2"><Check size={16} className="text-primary"/> სტრატეგია ინსტრუმენტამდე</span><span className="flex items-center gap-2"><Check size={16} className="text-primary"/> უსაფრთხოება დიზაინიდანვე</span><span className="flex items-center gap-2"><Check size={16} className="text-primary"/> გაზომვადი შედეგი</span></div></div>
        <div className="glass-panel self-center rounded-[2.5rem] p-6 sm:p-8"><div className="flex items-center gap-3 border-b border-slate-900/10 pb-5 dark:border-white/10"><div className="flex size-11 items-center justify-center rounded-2xl bg-primary/15 text-primary"><Orbit size={22}/></div><div><p className="text-sm font-bold text-slate-950 dark:text-white">IMI ოპერაციული რუკა</p><p className="text-xs text-slate-500 dark:text-slate-400">მოთხოვნიდან მოქმედებამდე</p></div></div><div className="mt-6">{flow.map(([number,title,text], index) => <div key={number} className="relative flex gap-4 pb-5 last:pb-0"><span className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-primary/15 text-xs font-bold text-primary">{number}</span>{index < flow.length - 1 && <i className="absolute left-5 top-10 h-5 border-l border-dashed border-primary/50"/>}<div><p className="font-bold text-slate-950 dark:text-white">{title}</p><p className="mt-1 text-sm text-slate-600 dark:text-slate-300">{text}</p></div></div>)}</div><p className="rounded-2xl border border-cyan-500/25 bg-cyan-400/10 p-4 text-sm leading-6 text-cyan-950 dark:text-cyan-50">AI არ ანაცვლებს თქვენს გუნდს. ის ამცირებს დაბრკოლებას, აჩქარებს რეაგირებას და რთულ გადაწყვეტილებას ისევ ადამიანთან ტოვებს.</p></div></div>
    </section>
    <section className="mx-auto max-w-7xl px-6 py-28 lg:px-8"><div className="grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><p className="text-xs font-bold tracking-[.2em] text-primary">მთავარი კითხვა</p><h2 className="mt-5 text-3xl font-bold leading-tight text-slate-950 dark:text-white sm:text-5xl">სად კარგავს თქვენი კომპანია დროს გადაწყვეტილებასა და მოქმედებას შორის?</h2></div><div className="grid gap-4 sm:grid-cols-2">{capabilities.map(([Icon,title,text]) => <article key={title} className="rounded-3xl border border-slate-900/10 bg-white/60 p-6 dark:border-white/10 dark:bg-white/[.035]"><Icon size={24} className="text-primary"/><h3 className="mt-10 text-lg font-bold text-slate-950 dark:text-white">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-600 dark:text-slate-300">{text}</p></article>)}</div></div></section>
    <section className="bg-slate-950 py-24 text-white"><div className="mx-auto max-w-7xl px-6 lg:px-8"><p className="text-xs font-bold tracking-[.2em] text-cyan-300">იდეიდან წარმოებაში</p><h2 className="mt-5 max-w-3xl text-3xl font-bold sm:text-5xl">არ ვყიდით prompt-ებს. ვაწვდით სისტემას, რომელსაც ბიზნესი მართავს.</h2><div className="mt-14 grid gap-px overflow-hidden rounded-3xl border border-white/10 bg-white/10 md:grid-cols-4">{[['01','აღმოჩენა','პროცესი, მომხმარებელი, მონაცემი და KPI.'],['02','დიზაინი','ინტეგრაცია, წვდომა, უსაფრთხოება და UX.'],['03','პილოტი','ვიწრო სცენარი, ხარისხის კონტროლი და უკუკავშირი.'],['04','მასშტაბირება','ახალი პროცესები, მონიტორინგი და ownership.']].map(([number,title,text]) => <div key={number} className="bg-slate-950 p-6"><p className="text-sm font-bold text-cyan-300">{number}</p><h3 className="mt-10 text-lg font-bold">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-300">{text}</p></div>)}</div></div></section>
    <section className="mx-auto max-w-7xl px-6 py-28 lg:px-8"><div className="flex items-end justify-between gap-6"><div><p className="text-xs font-bold tracking-[.2em] text-primary">ჩვენი პროდუქტები</p><h2 className="mt-5 text-3xl font-bold text-slate-950 dark:text-white sm:text-5xl">პროდუქტები, რომლებშიც ეს მიდგომა უკვე მუშაობს.</h2></div><Link href="/projects" className="text-sm font-bold text-slate-950 dark:text-white">ყველა პროექტი <ArrowUpRight className="inline" size={17}/></Link></div><div className="mt-12 grid gap-5 md:grid-cols-4">{[['Ertaoza','ქართული ხმოვანი და ენობრივი AI'],['CORD.GE','ტექსტის ხმად გარდაქმნა და API'],['Urbania','AI საკადასტრო და ურბანული აუდიტი'],['Breeding.ge','მონაცემებზე დაფუძნებული marketplace']].map(([name,text]) => <Link key={name} href={name === 'Urbania' ? '/projects/urbania' : '/projects'} className="glass-panel rounded-3xl p-6"><Bot className="text-primary" size={20}/><h3 className="mt-10 text-xl font-bold text-slate-950 dark:text-white">{name}</h3><p className="mt-3 text-sm leading-7 text-slate-600 dark:text-slate-300">{text}</p></Link>)}</div></section>
    <section className="mx-auto max-w-7xl px-6 pb-28 lg:px-8"><p className="text-xs font-bold tracking-[.2em] text-primary">ინსაითები</p><div className="mt-5 flex items-end justify-between gap-6"><h2 className="text-3xl font-bold text-slate-950 dark:text-white sm:text-5xl">ინსაითები, რომლებიც გადაწყვეტილებას აჩქარებს.</h2><Link href="/blog" className="text-sm font-bold text-slate-950 dark:text-white">ყველა ინსაითი</Link></div><div className="mt-12 grid gap-5 md:grid-cols-3">{[['/blog/rag-system-before-chatbot','ცოდნის AI / RAG','რატომ იწყება ძლიერი AI ასისტენტი ცოდნის არქიტექტურით'],['/blog/voice-ai-that-represents-your-brand','ხმოვანი AI','ხმოვანი AI, რომელიც თქვენს ბრენდს მართლა წარმოადგენს'],['/blog/ai-automation-roi-first-workflow','ავტომატიზაცია','სად იწყება AI ავტომატიზაციის რეალური ROI']].map(([href,tag,title]) => <Link key={href} href={href} className="rounded-3xl border border-slate-900/10 bg-white/60 p-7 dark:border-white/10 dark:bg-white/[.035]"><p className="text-xs font-bold tracking-[.15em] text-primary">{tag}</p><h3 className="mt-12 text-xl font-bold text-slate-950 dark:text-white">{title}</h3><span className="mt-7 inline-block text-sm font-bold text-slate-950 dark:text-white">წაკითხვა →</span></Link>)}</div></section>
    <section className="mx-auto max-w-5xl px-6 pb-28 lg:px-8"><div className="rounded-[2rem] border border-slate-900/10 bg-white/65 p-8 dark:border-white/10 dark:bg-white/[.035] sm:p-12"><p className="text-xs font-bold tracking-[.2em] text-primary">ხშირი კითხვები</p><h2 className="mt-5 text-3xl font-bold text-slate-950 dark:text-white">AI პროექტის დაწყებამდე</h2><div className="mt-10 divide-y divide-slate-900/10 dark:divide-white/10">{questions.map(({question,answer}) => <div key={question} className="py-6"><h3 className="font-bold text-slate-950 dark:text-white">{question}</h3><p className="mt-3 text-sm leading-7 text-slate-600 dark:text-slate-300">{answer}</p></div>)}</div><Link href="/consultation" className="mt-8 inline-flex items-center gap-2 rounded-xl bg-slate-950 px-5 py-3 text-sm font-bold text-white dark:bg-white dark:text-slate-950">დაჯავშნეთ კონსულტაცია <ArrowUpRight size={17}/></Link></div></section>
  </main>;
}
