import type { Metadata } from 'next';
import { ArrowDownRight, ArrowUpRight, Bot, Check, CircleDotDashed, Database, Headphones, Sparkles, Workflow } from 'lucide-react';
import { setRequestLocale } from 'next-intl/server';
import { Link } from '@/i18n/routing';
import FAQStructuredData from '@/components/FAQStructuredData';

export const metadata: Metadata = { title: 'AI სისტემები ბიზნესისთვის საქართველოში', description: 'IMI.GE ქმნის ხმოვან AI ასისტენტებს, RAG სისტემებს, AI CRM ინტეგრაციასა და ბიზნესის ავტომატიზაციას საქართველოს კომპანიებისთვის.' };

const questions = [
  { question: 'რით იწყება AI ინტეგრაცია ბიზნესში?', answer: 'ერთი რეალური პროცესით, რომლის დროსაც იკარგება დრო, კონტექსტი ან შემოსავალი. შემდეგ ვგეგმავთ მონაცემის საზღვარს, ადამიანის ჩართულობას და საზომ შედეგს.' },
  { question: 'შეუძლია AI-ს ქართულად მუშაობა?', answer: 'დიახ. AI სისტემა შეიძლება მოერგოს ქართულ ენას, თქვენს ტერმინოლოგიას, CRM-სა და მომსახურების წესებს.' },
  { question: 'როგორ იცავთ კომპანიის მონაცემებს?', answer: 'წვდომა, ცოდნის წყარო, ადამიანის დამტკიცება და ხარისხის კონტროლი განისაზღვრება არქიტექტურის ეტაპზევე.' },
];

const signals = [['ხმოვანი AI', 'მომხმარებლის მოთხოვნა პასუხად იქცევა'], ['RAG / ცოდნის ფენა', 'გუნდი პოულობს სანდო კონტექსტს'], ['AI CRM', 'ყველა ლიდი იღებს სწორ მომდევნო ნაბიჯს'], ['აგენტული ოპერაციები', 'განმეორებადი სამუშაო ნაკლებად ხელით სრულდება']];

export default async function HomePage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  setRequestLocale(locale);
  return <main className="overflow-hidden"><FAQStructuredData items={questions}/>
    <section className="relative min-h-[900px] bg-[#070707] px-4 pb-16 pt-32 text-[#fffaf4] sm:px-6 lg:pt-40"><div className="absolute inset-0 opacity-30 [background-image:linear-gradient(rgba(255,255,255,.13)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.13)_1px,transparent_1px)] [background-size:64px_64px]"/><div className="absolute -left-24 top-28 size-[28rem] rounded-full bg-primary/35 blur-[120px]"/><div className="absolute -right-32 bottom-0 size-[30rem] rounded-full bg-secondary/15 blur-[120px]"/>
      <div className="relative mx-auto max-w-7xl"><div className="grid gap-12 lg:grid-cols-[1.2fr_.8fr]"><div><p className="font-heading inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-4 py-2 text-xs font-bold tracking-[.18em]"><Sparkles size={14} className="text-secondary"/> AI / საქართველო / 2026</p><h1 className="mt-10 max-w-5xl text-5xl font-bold leading-[.9] tracking-[-.055em] sm:text-7xl xl:text-8xl">თქვენი კომპანია არ არის <span className="text-primary">workflow.</span><span className="block text-secondary">ის ცოცხალი სისტემა.</span></h1><p className="mt-9 max-w-2xl text-lg leading-8 text-slate-300">IMI.GE აერთიანებს ხმის, ცოდნის, CRM-ისა და ავტომატიზაციის ფენებს, რომ ბიზნესმა ნაკლები friction-ით იმუშაოს და მეტი სიზუსტით გადაწყვიტოს.</p><div className="mt-11 flex flex-col gap-3 sm:flex-row"><Link href="/consultation" className="font-heading inline-flex items-center justify-center gap-3 rounded-full bg-primary px-7 py-4 text-sm font-bold text-white transition hover:scale-[1.02] hover:bg-[#ff805f]">დავიწყოთ AI სესიით <ArrowUpRight size={18}/></Link><Link href="/projects" className="font-heading inline-flex items-center justify-center gap-3 rounded-full border border-white/25 px-7 py-4 text-sm font-bold text-white transition hover:bg-white hover:text-[#04132e]">ნახეთ მოქმედი პროდუქტები <ArrowDownRight size={18}/></Link></div></div>
        <aside className="relative self-end overflow-hidden rounded-[2.5rem] border border-white/15 bg-white/[.07] p-6 backdrop-blur-xl sm:p-8"><div className="flex items-center justify-between"><span className="font-heading text-xs font-bold tracking-[.18em] text-secondary">სისტემის სიგნალი</span><span className="flex items-center gap-2 text-xs text-slate-300"><i className="size-2 rounded-full bg-secondary shadow-[0_0_14px_#ffb08f]"/> აქტიური</span></div><div className="mt-10 space-y-3">{signals.map(([title, text], index) => <div key={title} className="group flex gap-4 rounded-2xl border border-white/10 bg-black/15 p-4 transition hover:-translate-x-1 hover:border-secondary/60"><span className="font-heading grid size-8 shrink-0 place-items-center rounded-full bg-white text-xs font-bold text-[#101010]">0{index + 1}</span><div><p className="font-heading text-sm font-bold">{title}</p><p className="mt-1 text-xs leading-6 text-slate-300">{text}</p></div></div>)}</div><div className="mt-7 border-t border-white/10 pt-5 text-sm text-slate-300"><span className="font-heading text-secondary">შედეგი:</span> მონაცემი ნაკლებად იკარგება. გადაწყვეტილება ნაკლებად გვიანდება.</div></aside></div>
      <div className="mt-20 grid gap-px overflow-hidden rounded-[2rem] border border-white/15 bg-white/10 md:grid-cols-4">{[['01','აღმოჩენა','ვპოულობთ ყველაზე ძვირ bottleneck-ს.'],['02','კონტექსტი','ვაერთიანებთ ცოდნასა და მონაცემს.'],['03','მოქმედება','AI სწორ სისტემაში წერს და გზავნის.'],['04','კონტროლი','გუნდი მართავს ხარისხს და გამონაკლისს.']].map(([number,title,text]) => <div key={number} className="bg-[#070707]/80 p-6"><p className="font-heading text-xs font-bold text-primary">{number}</p><h2 className="mt-10 text-lg font-bold">{title}</h2><p className="mt-3 text-sm leading-7 text-slate-300">{text}</p></div>)}</div></div>
    </section>
    <section className="relative mx-auto max-w-7xl px-6 py-28 lg:px-8"><div className="grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><div className="lg:sticky lg:top-32 lg:h-fit"><p className="font-heading text-xs font-bold tracking-[.2em] text-primary">რას ვაშენებთ</p><h2 className="mt-5 text-4xl font-bold leading-tight text-slate-950 dark:text-white">ოთხი ფენა, ერთი კონკურენტული უპირატესობა.</h2><p className="mt-6 leading-8 text-slate-600 dark:text-slate-300">არ ვამატებთ AI-ს უბრალოდ იმისთვის, რომ AI გქონდეთ. ვაშენებთ სისტემას, სადაც ყოველი ფენა პირდაპირი ბიზნეს-შედეგისთვის მუშაობს.</p><Link href="/services" className="font-heading mt-8 inline-flex items-center gap-2 text-sm font-bold text-slate-950 dark:text-white">ყველა სერვისი <ArrowUpRight size={17}/></Link></div><div className="grid gap-4 sm:grid-cols-2">{[[Headphones,'ხმოვანი გამოცდილება','ხმა, ჩატი და call flow, რომელიც ადამიანს სწორი კონტექსტით ხვდება.'],[Database,'ცოდნის ინტელექტი','RAG სისტემა, რომელიც პასუხს რეალური დოკუმენტიდან ამზადებს.'],[Bot,'AI CRM','ლიდის შეფასება, გაყიდვების სიგნალი და შემდეგი მოქმედება.'],[Workflow,'ავტომატური ოპერაციები','აგენტები, რომლებიც წესს მიჰყვება და გამონაკლისს გუნდს აბრუნებს.']].map(([Icon,title,text], index) => { const Component = Icon as typeof Headphones; return <article key={title as string} className={`rounded-[2rem] p-7 ${index === 1 || index === 2 ? 'bg-[#101010] text-white' : 'border border-slate-900/10 bg-white/70 text-slate-950 dark:border-white/10 dark:bg-white/[.04] dark:text-white'}`}><Component size={28} className={index === 1 || index === 2 ? 'text-secondary' : 'text-primary'}/><p className="font-heading mt-16 text-xl font-bold">{title as string}</p><p className={`mt-4 text-sm leading-7 ${index === 1 || index === 2 ? 'text-slate-300' : 'text-slate-600 dark:text-slate-300'}`}>{text as string}</p></article>})}</div></div></section>
    <section className="bg-primary px-6 py-24 text-white lg:px-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-10 md:flex-row md:items-end"><div><p className="font-heading text-xs font-bold tracking-[.2em] text-[#04132e]">AI მზადყოფნა</p><h2 className="mt-5 max-w-3xl text-4xl font-bold leading-tight sm:text-6xl">პირველი ნაბიჯი არ არის მოდელის არჩევა.</h2><p className="mt-6 max-w-xl leading-8 text-white/85">ის არის სწორად დასმული კითხვა: სად არის თქვენი ბიზნესის ყველაზე მნიშვნელოვანი friction?</p></div><Link href="/ai-readiness" className="font-heading inline-flex shrink-0 items-center justify-center gap-2 rounded-full bg-[#04132e] px-6 py-4 text-sm font-bold text-white transition hover:bg-white hover:text-[#04132e]">შეაფასეთ მზადყოფნა <ArrowUpRight size={18}/></Link></div></section>
    <section className="mx-auto max-w-7xl px-6 py-28 lg:px-8"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="font-heading text-xs font-bold tracking-[.2em] text-primary">სისტემები მოქმედებაში</p><h2 className="mt-5 text-4xl font-bold text-slate-950 dark:text-white">ჩვენი პროდუქტები არ არის მაკეტები.</h2></div><Link href="/projects" className="font-heading text-sm font-bold text-slate-950 dark:text-white">ყველა პროექტი →</Link></div><div className="mt-12 grid gap-4 md:grid-cols-4">{[['Ertaoza','ქართული language AI'],['CORD.GE','ხმის გენერაცია და API'],['Urbania','საკადასტრო AI აუდიტი'],['Breeding.ge','სანდო marketplace']].map(([name, detail], index) => <Link key={name} href={name === 'Urbania' ? '/projects/urbania' : '/projects'} className="group relative min-h-64 overflow-hidden rounded-[2rem] bg-[#101010] p-6 text-white transition hover:-translate-y-2"><span className="absolute -right-4 -top-8 text-[10rem] font-bold text-white/[.04]">0{index + 1}</span><p className="font-heading text-xs font-bold tracking-[.16em] text-secondary">პროდუქტის სისტემა</p><h3 className="mt-24 text-2xl font-bold">{name}</h3><p className="mt-2 text-sm text-slate-300">{detail}</p><ArrowUpRight className="absolute bottom-6 right-6 text-primary" size={22}/></Link>)}</div></section>
    <section className="mx-auto max-w-5xl px-6 pb-28 lg:px-8"><div className="rounded-[2.5rem] border border-slate-900/10 bg-white/75 p-8 dark:border-white/10 dark:bg-white/[.04] sm:p-12"><p className="font-heading text-xs font-bold tracking-[.2em] text-primary">სანამ დავიწყებთ</p><h2 className="mt-5 text-3xl font-bold text-slate-950 dark:text-white">ხშირი კითხვები AI სისტემებზე</h2><div className="mt-8 divide-y divide-slate-900/10 dark:divide-white/10">{questions.map((item) => <div key={item.question} className="py-6"><h3 className="font-heading font-bold text-slate-950 dark:text-white">{item.question}</h3><p className="mt-3 leading-7 text-slate-600 dark:text-slate-300">{item.answer}</p></div>)}</div><Link href="/consultation" className="font-heading mt-8 inline-flex items-center gap-2 rounded-full bg-primary px-6 py-4 text-sm font-bold text-white">დაჯავშნეთ AI სესია <ArrowUpRight size={18}/></Link></div></section>
  </main>;
}
